// SELVA CRACKERS 2026 catalogue
// Source: user-provided 2026 price list.
// Items 44 and 52 have no printed price; item 171 is printed as 450/500,
// so those three are intentionally disabled until a single selling price is confirmed.

const categoryOrder = [
  "Sparklers",
  "Fancy Sparklers",
  "Ground Chakkars",
  "Flower Pots",
  "Fancy Flower Pots",
  "Twinkling Star",
  "Bijili",
  "Sound Crackers",
  "Rocket",
  "Bombs",
  "Elite Series",
  "Colour Matches",
  "Ring Cap & Serpent Eggs",
  "Chotaa Fancy",
  "2 Sky Shooters",
  "3Â½\" Rainbow Sky",
  "4\" Mega Sky",
  "Combo Aerial Shot",
  "Multi Shot",
  "New Version",
  "Fancy Multi Shots",
  "Gift Box"
];

const products = [
  { id: 1, name: "7 cm Electric sparklers", tamilName: "7 à®šà¯†.à®®à¯€. à®šà®¾à®¤à®¾ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 24, unit: "Pkt", netRate: false, available: true },
  { id: 2, name: "7 cm Colour sparklers", tamilName: "7 à®šà¯†.à®®à¯€. à®•à®²à®°à¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 26, unit: "Pkt", netRate: false, available: true },
  { id: 3, name: "7 cm Green sparklers", tamilName: "7 à®šà¯†.à®®à¯€. à®ªà®šà¯à®šà¯ˆ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 32, unit: "Pkt", netRate: false, available: true },
  { id: 4, name: "7 cm Red sparklers", tamilName: "7 à®šà¯†.à®®à¯€. à®šà®¿à®µà®ªà¯à®ªà¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 35, unit: "Pkt", netRate: false, available: true },
  { id: 5, name: "10 cm Electric Sparklers", tamilName: "10 à®šà¯†.à®®à¯€. à®šà®¾à®¤à®¾ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 39, unit: "Pkt", netRate: false, available: true },
  { id: 6, name: "10 cm Colour Sparklers", tamilName: "10 à®šà¯†.à®®à¯€. à®•à®²à®°à¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 45, unit: "Pkt", netRate: false, available: true },
  { id: 7, name: "10 cm Green Sparklers", tamilName: "10 à®šà¯†.à®®à¯€. à®ªà®šà¯à®šà¯ˆ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 48, unit: "Pkt", netRate: false, available: true },
  { id: 8, name: "10 cm Red Sparklers", tamilName: "10 à®šà¯†.à®®à¯€. à®šà®¿à®µà®ªà¯à®ªà¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 54, unit: "Pkt", netRate: false, available: true },
  { id: 9, name: "15 cm Electric Sparklers", tamilName: "15 à®šà¯†.à®®à¯€. à®šà®¾à®¤à®¾ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 104, unit: "Pkt", netRate: false, available: true },
  { id: 10, name: "15 cm Colour Sparklers", tamilName: "15 à®šà¯†.à®®à¯€. à®•à®²à®°à¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 116, unit: "Pkt", netRate: false, available: true },
  { id: 11, name: "15 cm Green Sparklers", tamilName: "15 à®šà¯†.à®®à¯€. à®ªà®šà¯à®šà¯ˆ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 128, unit: "Pkt", netRate: false, available: true },
  { id: 12, name: "15 cm Red Sparklers", tamilName: "15 à®šà¯†.à®®à¯€. à®šà®¿à®µà®ªà¯à®ªà¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 140, unit: "Pkt", netRate: false, available: true },
  { id: 13, name: "30 cm Electric Sparklers", tamilName: "30 à®šà¯†.à®®à¯€. à®šà®¾à®¤à®¾ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 108, unit: "Pkt", netRate: false, available: true },
  { id: 14, name: "30 cm Colour Sparklers", tamilName: "30 à®šà¯†.à®®à¯€. à®•à®²à®°à¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 15, name: "30 cm Green Sparklers", tamilName: "30 à®šà¯†.à®®à¯€. à®ªà®šà¯à®šà¯ˆ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 132, unit: "Pkt", netRate: false, available: true },
  { id: 16, name: "30 cm Red Sparklers", tamilName: "30 à®šà¯†.à®®à¯€. à®šà®¿à®µà®ªà¯à®ªà¯ à®•à®®à¯à®ªà®¿", category: "Sparklers", price: 142, unit: "Pkt", netRate: false, available: true },
  { id: 17, name: "50 cm Electric", tamilName: "50 à®šà¯†.à®®à¯€. à®Žà®²à®•à¯à®Ÿà¯à®°à®¿à®•à¯", category: "Sparklers", price: 308, unit: "Pkt", netRate: false, available: true },
  { id: 18, name: "50 cm Green", tamilName: "50 à®šà¯†.à®®à¯€. à®ªà®šà¯à®šà¯ˆ", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 19, name: "50 cm Colour", tamilName: "50 à®šà¯†.à®®à¯€. à®•à®²à®°à¯", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 20, name: "10cmMiranda Orange/Mercury/Japan", tamilName: "10 à®šà¯†.à®®à¯€. à®®à®¿à®°à®¾à®£à¯à®Ÿà®¾ à®†à®°à®žà¯à®šà¯ / à®®à¯†à®°à¯à®•à¯à®°à®¿ / à®œà®ªà¯à®ªà®¾à®©à¯", category: "Fancy Sparklers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 21, name: "50 cm Electric", tamilName: "50 à®šà¯†.à®®à¯€. à®Žà®²à®•à¯à®Ÿà¯à®°à®¿à®•à¯", category: "Fancy Sparklers", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 22, name: "50 cm Crackling", tamilName: "50 à®šà¯†.à®®à¯€. à®•à®¿à®°à®¾à®•à¯à®²à®¿à®™à¯", category: "Fancy Sparklers", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 23, name: "50 cm 5 in 1 Colour", tamilName: "50 à®šà¯†.à®®à¯€. 5 à®‡à®©à¯ 1", category: "Fancy Sparklers", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 24, name: "75 cm Electric", tamilName: "75 à®šà¯†.à®®à¯€. à®Žà®²à®•à¯à®Ÿà¯à®°à®¿à®•à¯", category: "Fancy Sparklers", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 25, name: "75 cm Crackling", tamilName: "75 à®šà¯†.à®®à¯€. à®•à®¿à®°à®¾à®•à¯à®²à®¿à®™à¯", category: "Fancy Sparklers", price: 620, unit: "Pkt", netRate: false, available: true },
  { id: 26, name: "75 cm 5 in 1 Colour", tamilName: "75 à®šà¯†.à®®à¯€. 5 à®‡à®©à¯ 1 à®•à®²à®°à¯", category: "Fancy Sparklers", price: 675, unit: "Pkt", netRate: false, available: true },
  { id: 27, name: "Dancing Rose (Ele)", tamilName: "à®Ÿà®¾à®©à¯à®šà®¿à®™à¯ à®°à¯‹à®¸à¯ à®Žà®²à®•à¯à®Ÿà¯", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 28, name: "Dancing Rose (R & W)", tamilName: "à®Ÿà®¾à®©à¯à®šà®¿à®™à¯ à®°à¯‹à®¸à¯ (R & W)", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 29, name: "Ground Chakkar Big", tamilName: "à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®ªà¯†à®°à®¿à®¯à®¤à¯", category: "Ground Chakkars", price: 80, unit: "Pkt", netRate: false, available: true },
  { id: 30, name: "Ground Chakkar Ashoka", tamilName: "à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®…à®šà¯‹à®•à®¾", category: "Ground Chakkars", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 31, name: "Ground Chakkar Special", tamilName: "à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®¸à¯à®ªà¯†à®·à®²à¯", category: "Ground Chakkars", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 32, name: "Ground Chakkar Deluxe", tamilName: "à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®Ÿà¯€à®²à®•à¯à®¸à¯", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 33, name: "Anandaâ€™s Ground Chakkar Spl", tamilName: "à®†à®©à®¨à¯à®¤à®¾à®¸à¯ à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®¸à¯à®ªà¯†à®·à®²à¯", category: "Ground Chakkars", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 34, name: "Anandaâ€™s Classic Wheel", tamilName: "à®†à®©à®¨à¯à®¤à®¾à®¸à¯ à®•à®¿à®³à®¾à®šà®¿à®•à¯ à®µà¯€à®²à¯", category: "Ground Chakkars", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 35, name: "Rottas Wheel - Ayyan", tamilName: "à®°à¯‹à®Ÿà¯à®Ÿà®¸à¯ à®µà¯€à®²à¯ - à®…à®¯à¯à®¯à®©à¯", category: "Ground Chakkars", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 36, name: "Whistling Wheel - Ayyan", tamilName: "à®µà®¿à®šà®¿à®²à®¿à®™à¯ à®µà¯€à®²à¯ - à®…à®¯à¯à®¯à®©à¯", category: "Ground Chakkars", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 37, name: "Ananda's 3-1 Honda", tamilName: "à®†à®©à®¨à¯à®¤à®¾à®¸à¯ 3-1 à®¹à¯‹à®£à¯à®Ÿà®¾", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 38, name: "Ground Chakkar Special Green", tamilName: "à®¤à®°à¯ˆà®šà¯à®šà®•à¯à®•à®°à®®à¯ à®¸à¯à®ªà¯†à®·à®²à¯ à®ªà®šà¯à®šà¯ˆ", category: "Ground Chakkars", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 39, name: "Anandaâ€™s Deluxe", tamilName: "à®†à®©à®¨à¯à®¤à®¾à®¸à¯ à®Ÿà¯€à®²à®•à¯à®¸à¯", category: "Ground Chakkars", price: 525, unit: "Pkt", netRate: false, available: true },
  { id: 40, name: "Anandaâ€™s Roller Coaster", tamilName: "à®†à®©à®¨à¯à®¤à®¾à®¸à¯ à®°à¯‹à®²à®°à¯ à®•à¯‹à®¸à¯à®Ÿà®°à¯", category: "Ground Chakkars", price: 430, unit: "Pkt", netRate: false, available: true },
  { id: 41, name: "Silver Giant Wheel", tamilName: "à®šà®¿à®²à¯à®µà®°à¯ à®œà¯†à®¯à®¿à®£à¯à®Ÿà¯ à®µà¯€à®²à¯", category: "Ground Chakkars", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 42, name: "Flower Pots Small", tamilName: "à®ªà¯‚à®šà¯à®šà®Ÿà¯à®Ÿà®¿ à®šà®¿à®±à®¿à®¯à®¤à¯", category: "Flower Pots", price: 110, unit: "Pkt", netRate: false, available: true },
  { id: 43, name: "Flower Pots Big", tamilName: "à®ªà¯‚à®šà¯à®šà®Ÿà¯à®Ÿà®¿ à®ªà¯†à®°à®¿à®¯à®¤à¯", category: "Flower Pots", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 44, name: "Flower Pots Big Parasakthi", tamilName: "à®ªà¯‚à®šà¯à®šà®Ÿà¯à®Ÿà®¿ à®ªà¯†à®°à®¿à®¯à®¤à¯ à®ªà®°à®¾à®šà®•à¯à®¤à®¿", category: "Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 45, name: "Flower Pots Special", tamilName: "à®ªà¯‚à®šà¯à®šà®Ÿà¯à®Ÿà®¿ à®¸à¯à®ªà¯†à®·à®²à¯", category: "Flower Pots", price: 200, unit: "Pkt", netRate: false, available: true },
  { id: 46, name: "Flower Pots Ashoka", tamilName: "à®ªà¯‚à®šà¯à®šà®Ÿà¯à®Ÿà®¿ à®…à®šà¯‹à®•à®¾", category: "Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 47, name: "F/P DLX (5 Pcs)", tamilName: "F/P à®Ÿà¯€à®²à®•à¯à®¸à¯ (5 Pcs)", category: "Flower Pots", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 48, name: "Colour Koti", tamilName: "à®•à®²à®°à¯ à®•à¯‹à®Ÿà¯à®Ÿà®¿", category: "Flower Pots", price: 495, unit: "Pkt", netRate: false, available: true },
  { id: 49, name: "Colour Changing", tamilName: "à®•à®²à®°à¯ à®šà¯‡à®žà¯à®šà®¿à®™à¯", category: "Flower Pots", price: 320, unit: "Pkt", netRate: false, available: true },
  { id: 50, name: "Crackling Tree", tamilName: "à®•à®¿à®°à®¾à®•à¯à®²à®¿à®™à¯ à®Ÿà¯à®°à¯€", category: "Flower Pots", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 51, name: "Toys Fountion", tamilName: "à®Ÿà®¾à®¯à¯à®¸à¯ à®ªà®µà¯à®£à¯à®Ÿà®©à¯", category: "Flower Pots", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 52, name: "Colour Koti Green (5 Pcs)", tamilName: "à®•à®²à®°à¯ à®•à¯‹à®Ÿà¯à®Ÿà®¿ à®ªà®šà¯à®šà¯ˆ (5 à®ªà¯€à®¸à¯)", category: "Fancy Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 53, name: "Colour Koti (10 Pcs)", tamilName: "à®•à®²à®°à¯ à®•à¯‹à®Ÿà¯à®Ÿà®¿ (10 à®ªà¯€à®¸à¯)", category: "Fancy Flower Pots", price: 1100, unit: "Pkt", netRate: false, available: true },
  { id: 54, name: "Coluour Koti (5 Pcs) Deluxe", tamilName: "à®•à®²à®°à¯ à®•à¯‹à®Ÿà¯à®Ÿà®¿ (5 à®ªà¯€à®¸à¯) à®Ÿà¯€à®²à®•à¯à®¸à¯", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 55, name: "Coluour Koti (10 Pcs) Deluxe", tamilName: "à®•à®²à®°à¯ à®•à¯‹à®Ÿà¯à®Ÿà®¿ (10 à®ªà¯€à®¸à¯) à®Ÿà¯€à®²à®•à¯à®¸à¯", category: "Fancy Flower Pots", price: 900, unit: "Pkt", netRate: false, available: true },
  { id: 56, name: "Skype / Twitter", tamilName: "à®¸à¯à®•à¯ˆà®ªà¯ / à®Ÿà¯à®µà®¿à®Ÿà¯à®Ÿà®°à¯", category: "Fancy Flower Pots", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 57, name: "Fantasy Peacock", tamilName: "à®ªà®¾à®£à¯à®Ÿà®¸à®¿ à®ªà¯€à®•à®¾à®•à¯", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 58, name: "Jolly Ranger", tamilName: "à®œà®¾à®²à®¿ à®°à¯‡à®žà¯à®šà®°à¯", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 59, name: "Leaman Tree =Poppings", tamilName: "à®²à¯†à®®à®©à¯ à®Ÿà¯à®°à¯€ à®ªà®¾à®ªà¯à®ªà®¿à®™à¯à®¸à¯", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 60, name: "Tri Colour Fountatin", tamilName: "à®¤à¯à®°à®¿ à®•à®²à®°à¯ à®ªà®µà¯à®£à¯à®Ÿà®©à¯", category: "Fancy Flower Pots", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 61, name: "Selfie Stick (5Pcs) Ananda's", tamilName: "à®šà¯†à®²à¯à®ªà®¿ à®¸à¯à®Ÿà®¿à®•à¯ (5 à®ªà¯€à®¸à¯) à®†à®©à®¨à¯à®¤à®¾à®¸à¯", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 62, name: "Selfie Stick (5Pcs)", tamilName: "à®šà¯†à®²à¯à®ªà®¿ à®¸à¯à®Ÿà®¿à®•à¯ (5 à®ªà¯€à®¸à¯)", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 63, name: "1Â½â€ Twinkling Star", tamilName: "1Â½â€ à®šà®¾à®Ÿà¯à®Ÿà¯ˆ", category: "Twinkling Star", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 64, name: "4â€ Twinkling Star", tamilName: "4â€ à®šà®¾à®Ÿà¯à®Ÿà¯ˆ", category: "Twinkling Star", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 65, name: "Roman Candles", tamilName: "à®°à¯‹à®®à®©à¯ à®•à¯‡à®£à¯à®Ÿà®¿à®²à¯", category: "Twinkling Star", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 66, name: "Bijili (50 Pcs)", tamilName: "à®ªà®¿à®œà®¿à®²à®¿ (50 Pcs)", category: "Bijili", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 67, name: "Red Bijili (100 Pcs)", tamilName: "à®šà®¿à®µà®ªà¯à®ªà¯ à®ªà®¿à®œà®¿à®²à®¿ (100 Pcs)", category: "Bijili", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 68, name: "Stripped Bijili (100 Pcs)", tamilName: "à®¸à¯à®Ÿà¯à®°à¯ˆà®ªà¯à®Ÿà¯ à®ªà®¿à®œà®¿à®²à®¿ (100 Pcs)", category: "Bijili", price: 70, unit: "Pkt", netRate: false, available: true },
  { id: 69, name: "2Â¾â€Bird", tamilName: "2Â¾â€ à®ªà¯‡à®°à¯à®Ÿà¯", category: "Sound Crackers", price: 20, unit: "Pkt", netRate: false, available: true },
  { id: 70, name: "3Â½â€Lakshmi", tamilName: "3Â½â€ à®²à®Ÿà¯à®šà¯à®®à®¿", category: "Sound Crackers", price: 30, unit: "Pkt", netRate: false, available: true },
  { id: 71, name: "4â€ Lakshmi", tamilName: "4â€ à®²à®Ÿà¯à®šà¯à®®à®¿", category: "Sound Crackers", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 72, name: "4â€ Lakshmi Deluxe", tamilName: "4â€ à®²à®Ÿà¯à®šà¯à®®à®¿ à®Ÿà¯€à®²à®•à¯à®¸à¯", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 73, name: "4â€ Gold Lakshmi", tamilName: "4â€ à®•à¯‹à®²à¯à®Ÿà¯ à®²à®Ÿà¯à®šà¯à®®à®¿", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 74, name: "Hulk", tamilName: "à®¹à®²à¯à®•à¯", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 75, name: "2 Sound", tamilName: "2 à®šà®µà¯à®£à¯à®Ÿà¯", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 76, name: "Bahubali", tamilName: "à®ªà®¾à®•à¯à®ªà®²à®¿", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 77, name: "Joker/ Lion", tamilName: "à®œà¯‹à®•à¯à®•à®°à¯ / à®²à®¯à®©à¯", category: "Sound Crackers", price: 100, unit: "Pkt", netRate: false, available: true },
  { id: 78, name: "Rocket Bomb", tamilName: "à®°à®¾à®•à¯à®•à¯†à®Ÿà¯ à®ªà®¾à®®à¯", category: "Rocket", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 79, name: "Whistling Rocket (5 Pcs)", tamilName: "à®µà®¿à®šà®¿à®²à®¿à®™à¯ à®°à®¾à®•à¯à®•à¯†à®Ÿà¯ (5 Pcs)", category: "Rocket", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 80, name: "Whistling Rocket (10 Pcs)", tamilName: "à®µà®¿à®šà®¿à®²à®¿à®™à¯ à®°à®¾à®•à¯à®•à¯†à®Ÿà¯ (10 Pcs)", category: "Rocket", price: 485, unit: "Pkt", netRate: false, available: true },
  { id: 81, name: "Fancy Peacock", tamilName: "à®ƒà®ªà¯‡à®©à¯à®šà®¿ à®ªà¯€à®•à®¾à®•à¯", category: "Rocket", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 82, name: "Tri colour fountatin Small", tamilName: "à®Ÿà¯à®°à¯ˆà®•à®²à®°à¯ à®ªà®µà¯à®£à¯à®Ÿà®©à¯ à®šà®¿à®±à®¿à®¯à®¤à¯", category: "Rocket", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 83, name: "Bullet Bomb", tamilName: "à®ªà¯à®²à¯à®²à®Ÿà¯ à®ªà®¾à®®à¯", category: "Bombs", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 84, name: "Atom Bomb", tamilName: "à®†à®Ÿà¯à®Ÿà®®à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 85, name: "Hydro Bomb", tamilName: "à®¹à¯ˆà®Ÿà¯à®°à¯‹ à®ªà®¾à®®à¯", category: "Bombs", price: 145, unit: "Pkt", netRate: false, available: true },
  { id: 86, name: "King of King", tamilName: "à®•à®¿à®™à¯ à®†à®ªà¯ à®•à®¿à®™à¯", category: "Bombs", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 87, name: "Marathan Bomb", tamilName: "à®®à®¾à®°à®¤à¯à®¤à®¾à®©à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 88, name: "Classic Bomb", tamilName: "à®•à®¿à®³à®¾à®šà®¿à®•à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 89, name: "Agni", tamilName: "à®œà¯‚à®°à®¾à®šà®¿à®•à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 395, unit: "Pkt", netRate: false, available: true },
  { id: 90, name: "555 Bomb", tamilName: "555 à®ªà®¾à®®à¯", category: "Bombs", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 91, name: "Killer Bomb", tamilName: "à®šà®¿à®²à¯à®µà®°à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 92, name: "D T S Bomb", tamilName: "à®Ÿà®¿ à®Ÿà®¿ à®Žà®¸à¯ à®ªà®¾à®®à¯", category: "Bombs", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 93, name: "Assorted Cartoon (10 Pcs)", tamilName: "à®…à®šà®¾à®°à¯à®Ÿà¯à®Ÿà®Ÿà¯ à®•à®¾à®°à¯à®Ÿà¯à®Ÿà¯‚à®©à¯ (10 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 94, name: "Electric Stone / Kit Kat", tamilName: "à®Žà®²à®•à¯à®Ÿà¯à®°à®¿à®•à¯ à®¸à¯à®Ÿà¯‹à®©à¯", category: "Elite Series", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 95, name: "Jee Boom Baa", tamilName: "à®œà¯€ à®ªà¯‚à®®à¯ à®ªà®¾", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 96, name: "Photo Flash", tamilName: "à®ªà¯‹à®Ÿà¯à®Ÿà¯‹ à®ªà®¿à®³à®¾à®·à¯", category: "Elite Series", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 97, name: "Selfie Stick (5 Pcs)", tamilName: "à®šà¯†à®²à¯à®ªà®¿ à®¸à¯à®Ÿà®¿à®•à¯ (5 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 98, name: "Child money bank", tamilName: "à®šà¯ˆà®²à¯à®Ÿà¯ à®®à®©à®¿ à®ªà¯‡à®™à¯à®•à¯", category: "Elite Series", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 99, name: "Drone", tamilName: "à®Ÿà¯à®°à¯‹à®©à¯", category: "Elite Series", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 100, name: "Pambaram (10 Pcs)", tamilName: "à®ªà®®à¯à®ªà®°à®®à¯ (10 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 101, name: "Helicoptar (5 Pcs)", tamilName: "à®¹à¯†à®²à®¿à®•à®¾à®ªà¯à®Ÿà®°à¯ (5 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 102, name: "Butterfly", tamilName: "à®ªà®Ÿà¯à®Ÿà®°à¯à®ªà®¿à®³à¯ˆ", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 103, name: "Sky Shot", tamilName: "à®¸à¯à®•à¯ˆ à®·à®¾à®Ÿà¯", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 104, name: "Killar Shot", tamilName: "à®•à®¿à®²à¯à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Elite Series", price: 270, unit: "Pkt", netRate: false, available: true },
  { id: 105, name: "Colour Fountain (5 Pcs)", tamilName: "à®•à®²à®°à¯ à®ªà®µà¯à®£à¯à®Ÿà®©à¯ (5 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 106, name: "Thriller Siren Big (3 Pcs)", tamilName: "à®¤à¯à®°à®¿à®²à¯à®²à®°à¯ à®šà¯ˆà®°à®©à¯ à®ªà®¿à®•à¯ (3 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 107, name: "Siren Small (3 Pcs)", tamilName: "à®šà¯ˆà®°à®©à¯ à®¸à¯à®®à®¾à®²à¯ (3 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 276, unit: "Pkt", netRate: false, available: true },
  { id: 108, name: "Siren Big (2 Pcs)", tamilName: "à®šà¯ˆà®°à®©à¯ à®ªà®¿à®•à¯ (2 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 109, name: "Tin Fountain", tamilName: "à®Ÿà®¿à®©à¯ à®ªà®µà¯à®£à¯à®Ÿà®©à¯", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 110, name: "Water Queen Falls", tamilName: "à®µà®¾à®Ÿà¯à®Ÿà®°à¯ à®•à¯à®¯à®¿à®©à¯ à®ªà®¾à®²à¯à®¸à¯", category: "Elite Series", price: 360, unit: "Pkt", netRate: false, available: true },
  { id: 111, name: "Colour Fog (5 Pcs)", tamilName: "à®•à®²à®°à¯ à®ªà¯‹à®•à¯ (5 à®ªà¯€à®¸à¯)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 112, name: "Pada Peacock", tamilName: "à®ªà®Ÿà®¾ à®ªà¯€à®•à®¾à®•à¯", category: "Elite Series", price: 840, unit: "Pkt", netRate: false, available: true },
  { id: 113, name: "Master Cricket Pat", tamilName: "à®®à®¾à®¸à¯à®Ÿà®°à¯ à®•à®¿à®°à®¿à®•à¯à®•à¯†à®Ÿà¯ à®ªà¯‡à®Ÿà¯", category: "Elite Series", price: 354, unit: "Pcs", netRate: false, available: true },
  { id: 114, name: "Robin Max Cone", tamilName: "à®°à®¾à®ªà®¿à®©à¯ à®®à¯‡à®•à¯à®¸à¯ à®•à¯‹à®©à¯", category: "Colour Matches", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 115, name: "Super King", tamilName: "à®šà¯‚à®ªà¯à®ªà®°à¯ à®•à®¿à®™à¯", category: "Colour Matches", price: 168, unit: "Pkt", netRate: false, available: true },
  { id: 116, name: "Classic 5 in 1", tamilName: "à®•à®¿à®³à®¾à®šà®¿à®•à¯ 5 à®‡à®©à¯ 1", category: "Colour Matches", price: 288, unit: "Pkt", netRate: false, available: true },
  { id: 117, name: "7 up Rainbow", tamilName: "7 up à®°à¯†à®¯à®¿à®©à¯à®ªà¯‹", category: "Colour Matches", price: 312, unit: "Pkt", netRate: false, available: true },
  { id: 118, name: "VIP 10 in 1 Laptop", tamilName: "à®µà®¿à®à®ªà®¿ 10 à®‡à®©à¯ 1 à®²à¯‡à®ªà¯à®Ÿà®¾à®ªà¯", category: "Colour Matches", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 119, name: "Roll cap", tamilName: "à®°à¯‹à®²à¯ à®•à¯‡à®ªà¯", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 120, name: "Black serpent Big", tamilName: "à®ªà®¿à®³à®¾à®•à¯ à®šà®°à¯à®ªà®£à¯à®Ÿà¯ à®ªà¯†à®°à®¿à®¯à®¤à¯", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 121, name: "Anaconda", tamilName: "à®…à®©à®•à¯‹à®£à¯à®Ÿà®¾", category: "Ring Cap & Serpent Eggs", price: 192, unit: "Pkt", netRate: false, available: true },
  { id: 122, name: "Epson", tamilName: "à®Žà®ªà¯à®šà®©à¯", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 123, name: "Fuji", tamilName: "à®ªà¯à®œà®¿", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 124, name: "Kodak", tamilName: "à®•à¯‹à®Ÿà®¾à®•à¯", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 125, name: "Canan", tamilName: "à®•à¯†à®©à®¾à®©à¯", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 126, name: "Yellow MG", tamilName: "à®®à®žà¯à®šà®³à¯ à®Žà®®à¯ à®œà®¿", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 127, name: "Orange Audi", tamilName: "à®†à®°à®žà¯à®šà¯ à®†à®Ÿà®¿", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 128, name: "Red Swift", tamilName: "à®šà®¿à®•à®ªà¯à®ªà¯ à®šà®¿à®ªà¯à®Ÿà¯", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 129, name: "Pink Jaguer", tamilName: "à®ªà®¿à®™à¯à®•à¯ à®œà®¾à®•à¯à®•à¯à®µà®¾à®°à¯", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 130, name: "Blue Land Rover", tamilName: "à®ªà¯à®³à¯‚ à®²à¯‡à®£à¯à®Ÿà¯ à®°à¯‹à®µà®°à¯", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 131, name: "Eagle", tamilName: "à®ˆà®•à®¿à®²à¯", category: "3Â½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 132, name: "Blood Shot", tamilName: "à®ªà®¿à®³à®Ÿà¯ à®·à®¾à®Ÿà¯", category: "3Â½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 133, name: "Stay Strong", tamilName: "à®¸à¯à®Ÿà¯‡ à®¸à¯à®Ÿà¯à®°à®¾à®™à¯", category: "3Â½\" Rainbow Sky", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 134, name: "Chori 3Â½Double Ball", tamilName: "à®šà¯‹à®°à®¿ 3Â½ à®Ÿà®ªà¯à®³à¯ à®ªà®¾à®²à¯", category: "3Â½\" Rainbow Sky", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 135, name: "Racing", tamilName: "à®°à¯‡à®šà®¿à®™à¯", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 136, name: "Hunter", tamilName: "à®¹à®£à¯à®Ÿà®°à¯", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 137, name: "Passion", tamilName: "à®ªà¯‡à®šà®¿à®¯à®©à¯", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 138, name: "Volley Ball", tamilName: "à®µà®¾à®²à®¿ à®ªà®¾à®²à¯", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 139, name: "Nayakara", tamilName: "à®¨à®¯à®¾à®•à®°à®¾", category: "4\" Mega Sky", price: 680, unit: "Pcs", netRate: false, available: true },
  { id: 140, name: "1â€Fanta(5 Pcs)", tamilName: "1â€ à®ƒà®ªà¯‡à®©à¯à®Ÿà®¾ (5 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 141, name: "1â€ DSLR (5 Pcs)", tamilName: "1â€ à®Ÿà®¿ à®Žà®¸à¯ à®Žà®²à¯ à®†à®°à¯ (5 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 575, unit: "Pkt", netRate: false, available: true },
  { id: 142, name: "2â€ Combo (3 Pcs)", tamilName: "2â€ à®•à®¾à®®à¯à®ªà¯‹ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 143, name: "2â€ Combo Elite (3 Pcs)", tamilName: "2â€ à®•à®¾à®®à¯à®ªà¯‹ à®Žà®²à¯ˆà®Ÿà¯ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 144, name: "Anandas 3â€ Comets (1 Pcs)", tamilName: "à®†à®©à®¨à¯à®¤à®¾ 3â€ à®•à®¾à®®à¯†à®Ÿà¯à®¸à¯ (1 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 145, name: "Anandas 3â€Double ball (1Pcs)", tamilName: "à®†à®©à®¨à¯à®¤à®¾ 3â€ à®Ÿà®ªà¯à®³à¯à®ªà®¾à®²à¯ (1 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 1000, unit: "Pkt", netRate: false, available: true },
  { id: 146, name: "2Â¼â€ Tangled (3 Pcs)Anandaâ€™s", tamilName: "2Â¼â€ à®Ÿà¯‡à®™à¯à®•à®¿à®²à¯à®Ÿà¯ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 147, name: "2Â¼â€ Ice age (3 Pcs)Anandaâ€™s", tamilName: "2Â¼â€ à®à®¸à¯ à®à®œà¯ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 148, name: "2Â¾â€Cars (3 Pcs) Anandaâ€™s", tamilName: "2Â¾â€ à®•à®¾à®°à¯à®¸à¯ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 149, name: "2Â¾â€Tarzen (3 Pcs) Anandaâ€™s", tamilName: "2Â¾â€ à®Ÿà®¾à®°à¯à®šà®©à¯ (3 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 150, name: "3\" 8 Steps Captain America 1 Pcs", tamilName: "3â€ 8 à®¸à¯à®Ÿà¯†à®ªà¯à®¸à¯ à®…à®®à¯†à®°à®¿à®•à¯à®•à®¾ (1 à®ªà¯€à®¸à¯)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 151, name: "Mighty Sword Anandaâ€™s", tamilName: "à®®à¯ˆà®Ÿà¯à®Ÿà®¿à®¸à¯ à®¸à¯à®µà®¾à®°à¯à®Ÿà¯ à®†à®©à®¨à¯à®¤à®¾", category: "Combo Aerial Shot", price: 600, unit: "Box", netRate: false, available: true },
  { id: 152, name: "Dirates gun Anandaâ€™s", tamilName: "à®Ÿà¯ˆà®°à®•à¯à®Ÿà¯ à®•à®©à¯ à®†à®©à®¨à¯à®¤à®¾", category: "Combo Aerial Shot", price: 500, unit: "Box", netRate: false, available: true },
  { id: 153, name: "Five Falls", tamilName: "à®ªà¯ˆ à®ªà®¾à®²à¯à®¸à¯", category: "Multi Shot", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 154, name: "7 Wonders", tamilName: "7 à®µà¯Šà®£à¯à®Ÿà®°à¯à®¸à¯", category: "Multi Shot", price: 205, unit: "Pkt", netRate: false, available: true },
  { id: 155, name: "Space Warriors", tamilName: "à®¸à¯à®ªà¯‡à®¸à¯ à®µà¯‡à®°à®¿à®¯à®°à¯à®¸à¯", category: "Multi Shot", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 156, name: "7 Shot", tamilName: "7 à®·à®¾à®Ÿà¯", category: "Multi Shot", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 157, name: "12 Shots", tamilName: "12 à®·à®¾à®Ÿà¯à®¸à¯", category: "Multi Shot", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 158, name: "Kinder pop", tamilName: "à®•à®¿à®£à¯à®Ÿà®°à¯ à®ªà®¾à®ªà¯", category: "New Version", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 159, name: "Star Pots", tamilName: "à®¸à¯à®Ÿà®¾à®°à¯ à®ªà®¾à®Ÿà¯à®¸à¯", category: "New Version", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 160, name: "Golden Egg (2 Pcs)", tamilName: "à®•à¯‹à®²à¯à®Ÿà®©à¯ à®Žà®•à¯ (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 161, name: "Gun Spark (2 Pcs)", tamilName: "à®•à®©à¯ à®¸à¯à®ªà®¾à®°à¯à®•à¯ (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 162, name: "Gadayutham", tamilName: "à®•à®Ÿà®¾à®¯à¯à®¤à®®à¯", category: "New Version", price: 415, unit: "Pcs", netRate: false, available: true },
  { id: 163, name: "Feather Super", tamilName: "à®ªà¯†à®¤à®°à¯ à®šà¯‚à®ªà¯à®ªà®°à¯", category: "New Version", price: 215, unit: "Pcs", netRate: false, available: true },
  { id: 164, name: "Spl Guitor", tamilName: "à®¸à¯à®ªà¯†à®·à®²à¯ à®•à®¿à®Ÿà¯à®Ÿà®¾à®°à¯", category: "New Version", price: 420, unit: "Pcs", netRate: false, available: true },
  { id: 165, name: "Guitor Music Band", tamilName: "à®•à®¿à®Ÿà¯à®Ÿà®¾à®°à¯ à®®à®¿à®¯à¯‚à®šà®¿à®•à¯ à®ªà®¾à®£à¯à®Ÿà¯", category: "New Version", price: 600, unit: "Pcs", netRate: false, available: true },
  { id: 166, name: "Red Sun - Sun Feast (5 P-5W)", tamilName: "à®°à¯†à®Ÿà¯-à®šà®©à¯-à®šà®©à¯ à®ªà®¿à®¸à¯à®Ÿà¯ (5 P-5W)", category: "New Version", price: 385, unit: "Pcs", netRate: false, available: true },
  { id: 167, name: "Hand Shot", tamilName: "à®¹à¯‡à®£à¯à®Ÿà¯ à®·à®¾à®Ÿà¯", category: "New Version", price: 2450, unit: "Pcs", netRate: false, available: true },
  { id: 168, name: "CSK Bus Tricolour", tamilName: "CSK à®ªà®¸à¯ à®Ÿà¯à®°à¯ˆà®•à®²à®°à¯", category: "New Version", price: 580, unit: "Pcs", netRate: false, available: true },
  { id: 169, name: "15 Multi Colour Shot", tamilName: "15 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 275, unit: "Pcs", netRate: true, available: true },
  { id: 170, name: "25 Raider Shot", tamilName: "25 à®°à¯ˆà®Ÿà®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 350, unit: "Pcs", netRate: true, available: true },
  { id: 171, name: "30 Multi Colour Shot", tamilName: "30 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: null, unit: "Pcs", netRate: true, available: false, priceText: "â‚¹450 / â‚¹500" },
  { id: 172, name: "60 Multi Colour Shot", tamilName: "60 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 900, unit: "Pcs", netRate: true, available: true },
  { id: 173, name: "100 Multi Colour Shot", tamilName: "100 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 1600, unit: "Pcs", netRate: true, available: true },
  { id: 174, name: "120 Multi Colour Shot", tamilName: "120 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 1800, unit: "Pcs", netRate: true, available: true },
  { id: 175, name: "10 x 10 Anandaâ€™s Multi Colour Shot", tamilName: "10 x10 à®†à®©à®¨à¯à®¤à®¾'à®¸à¯ à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 3750, unit: "Pcs", netRate: true, available: true },
  { id: 176, name: "240 Multi Colour Shot", tamilName: "240 à®®à®²à¯à®Ÿà®¿ à®•à®²à®°à¯ à®·à®¾à®Ÿà¯", category: "Fancy Multi Shots", price: 3600, unit: "Pcs", netRate: true, available: true },
  { id: 177, name: "ICE AGE MINIONS19 ITEMS", tamilName: "à®à®¸à¯ à®à®œà¯ à®®à®¿à®©à®¿à®¯à®©à¯à®¸à¯", category: "Gift Box", price: 275, unit: "Box", netRate: true, available: true },
  { id: 178, name: "Dora 19 ITEMS", tamilName: "à®Ÿà¯‹à®°à®¾", category: "Gift Box", price: 300, unit: "Box", netRate: true, available: true },
  { id: 179, name: "Festival Box 20 ITEMS", tamilName: "à®ªà¯†à®¸à¯à®Ÿà®¿à®µà®²à¯ à®ªà®¾à®•à¯à®¸à¯", category: "Gift Box", price: 325, unit: "Box", netRate: true, available: true },
  { id: 180, name: "Mono 21 ITEMS", tamilName: "à®®à¯‹à®©à¯‹", category: "Gift Box", price: 350, unit: "Box", netRate: true, available: true },
  { id: 181, name: "Angry Birds 27 ITEMS", tamilName: "à®†à®™à¯à®•à®¿à®°à®¿ à®ªà¯‡à®°à¯à®Ÿà¯à®¸à¯", category: "Gift Box", price: 450, unit: "Box", netRate: true, available: true },
  { id: 182, name: "Avenger 28 ITEMS", tamilName: "à®…à®µà¯†à®žà¯à®šà®°à¯", category: "Gift Box", price: 475, unit: "Box", netRate: true, available: true },
  { id: 183, name: "Avator Super 30 ITEMS", tamilName: "à®…à®µà®¤à®¾à®°à¯ à®šà¯‚à®ªà¯à®ªà®°à¯", category: "Gift Box", price: 550, unit: "Box", netRate: true, available: true },
  { id: 184, name: "Hulk 36 ITEMS", tamilName: "à®¹à®²à¯à®•à¯", category: "Gift Box", price: 650, unit: "Box", netRate: true, available: true },
  { id: 185, name: "Angry Bird 40 ITEMS", tamilName: "à®†à®™à¯à®•à®¿à®°à®¿ à®ªà¯‡à®°à¯à®Ÿà¯", category: "Gift Box", price: 750, unit: "Box", netRate: true, available: true },
  { id: 186, name: "Paradise 45 ITEMS", tamilName: "à®ªà®¾à®°à®Ÿà¯ˆà®¸à¯", category: "Gift Box", price: 850, unit: "Box", netRate: true, available: true },
  { id: 187, name: "Wonderful 50 ITEMS", tamilName: "à®µà¯Šà®£à¯à®Ÿà®°à¯à®ªà¯à®²à¯", category: "Gift Box", price: 1050, unit: "Box", netRate: true, available: true },
  { id: 188, name: "Carnival 55 ITEMS", tamilName: "à®•à®¾à®°à¯à®©à®¿à®µà®²à¯", category: "Gift Box", price: 1250, unit: "Box", netRate: true, available: true },
  { id: 189, name: "VIP Champion 60 ITEMS", tamilName: "à®µà®¿à®à®ªà®¿ à®šà¯‡à®®à¯à®ªà®¿à®¯à®©à¯", category: "Gift Box", price: 1500, unit: "Box", netRate: true, available: true }
];


/* Global catalogue exports for reliable cross-script loading */
if (typeof window !== "undefined") {
    window.categoryOrder = categoryOrder;
    window.products = products;
}