// SELVA CRACKERS 2026 catalogue
// Source: user-provided 2026 price list.
// Items 44 and 52 have no printed price; item 171 is printed as 450/500,
// so those three are intentionally disabled until a single selling price is confirmed.

const categoryOrder = [
  "Sparklers",
  "Fancy Sparklers",
  "Ground Chakkars",
  "Flower Pots",
  "Fancy Flower Pots",
  "Twinkling Star",
  "Bijili",
  "Sound Crackers",
  "Rocket",
  "Bombs",
  "Elite Series",
  "Colour Matches",
  "Ring Cap & Serpent Eggs",
  "Chotaa Fancy",
  "2 Sky Shooters",
  "3Ã‚Â½\" Rainbow Sky",
  "4\" Mega Sky",
  "Combo Aerial Shot",
  "Multi Shot",
  "New Version",
  "Fancy Multi Shots",
  "Gift Box"
];

const products = [
  { id: 1, name: "7 cm Electric sparklers", tamilName: "7 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¾Ã Â®Â¤Ã Â®Â¾ Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 24, unit: "Pkt", netRate: false, available: true },
  { id: 2, name: "7 cm Colour sparklers", tamilName: "7 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 26, unit: "Pkt", netRate: false, available: true },
  { id: 3, name: "7 cm Green sparklers", tamilName: "7 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë† Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 32, unit: "Pkt", netRate: false, available: true },
  { id: 4, name: "7 cm Red sparklers", tamilName: "7 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¿Ã Â®ÂµÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 35, unit: "Pkt", netRate: false, available: true },
  { id: 5, name: "10 cm Electric Sparklers", tamilName: "10 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¾Ã Â®Â¤Ã Â®Â¾ Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 39, unit: "Pkt", netRate: false, available: true },
  { id: 6, name: "10 cm Colour Sparklers", tamilName: "10 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 45, unit: "Pkt", netRate: false, available: true },
  { id: 7, name: "10 cm Green Sparklers", tamilName: "10 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë† Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 48, unit: "Pkt", netRate: false, available: true },
  { id: 8, name: "10 cm Red Sparklers", tamilName: "10 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¿Ã Â®ÂµÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 54, unit: "Pkt", netRate: false, available: true },
  { id: 9, name: "15 cm Electric Sparklers", tamilName: "15 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¾Ã Â®Â¤Ã Â®Â¾ Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 104, unit: "Pkt", netRate: false, available: true },
  { id: 10, name: "15 cm Colour Sparklers", tamilName: "15 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 116, unit: "Pkt", netRate: false, available: true },
  { id: 11, name: "15 cm Green Sparklers", tamilName: "15 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë† Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 128, unit: "Pkt", netRate: false, available: true },
  { id: 12, name: "15 cm Red Sparklers", tamilName: "15 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¿Ã Â®ÂµÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 140, unit: "Pkt", netRate: false, available: true },
  { id: 13, name: "30 cm Electric Sparklers", tamilName: "30 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¾Ã Â®Â¤Ã Â®Â¾ Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 108, unit: "Pkt", netRate: false, available: true },
  { id: 14, name: "30 cm Colour Sparklers", tamilName: "30 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 15, name: "30 cm Green Sparklers", tamilName: "30 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë† Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 132, unit: "Pkt", netRate: false, available: true },
  { id: 16, name: "30 cm Red Sparklers", tamilName: "30 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å¡Ã Â®Â¿Ã Â®ÂµÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®â€¢Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿", category: "Sparklers", price: 142, unit: "Pkt", netRate: false, available: true },
  { id: 17, name: "50 cm Electric", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å½Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯Â", category: "Sparklers", price: 308, unit: "Pkt", netRate: false, available: true },
  { id: 18, name: "50 cm Green", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë†", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 19, name: "50 cm Colour", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 20, name: "10cmMiranda Orange/Mercury/Japan", tamilName: "10 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Â®Ã Â®Â¿Ã Â®Â°Ã Â®Â¾Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾ Ã Â®â€ Ã Â®Â°Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â¯Â / Ã Â®Â®Ã Â¯â€ Ã Â®Â°Ã Â¯ÂÃ Â®â€¢Ã Â¯ÂÃ Â®Â°Ã Â®Â¿ / Ã Â®Å“Ã Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â®Â¾Ã Â®Â©Ã Â¯Â", category: "Fancy Sparklers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 21, name: "50 cm Electric", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å½Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯Â", category: "Fancy Sparklers", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 22, name: "50 cm Crackling", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "Fancy Sparklers", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 23, name: "50 cm 5 in 1 Colour", tamilName: "50 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. 5 Ã Â®â€¡Ã Â®Â©Ã Â¯Â 1", category: "Fancy Sparklers", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 24, name: "75 cm Electric", tamilName: "75 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®Å½Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯Â", category: "Fancy Sparklers", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 25, name: "75 cm Crackling", tamilName: "75 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. Ã Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "Fancy Sparklers", price: 620, unit: "Pkt", netRate: false, available: true },
  { id: 26, name: "75 cm 5 in 1 Colour", tamilName: "75 Ã Â®Å¡Ã Â¯â€ .Ã Â®Â®Ã Â¯â‚¬. 5 Ã Â®â€¡Ã Â®Â©Ã Â¯Â 1 Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â", category: "Fancy Sparklers", price: 675, unit: "Pkt", netRate: false, available: true },
  { id: 27, name: "Dancing Rose (Ele)", tamilName: "Ã Â®Å¸Ã Â®Â¾Ã Â®Â©Ã Â¯ÂÃ Â®Å¡Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®Â°Ã Â¯â€¹Ã Â®Â¸Ã Â¯Â Ã Â®Å½Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 28, name: "Dancing Rose (R & W)", tamilName: "Ã Â®Å¸Ã Â®Â¾Ã Â®Â©Ã Â¯ÂÃ Â®Å¡Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®Â°Ã Â¯â€¹Ã Â®Â¸Ã Â¯Â (R & W)", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 29, name: "Ground Chakkar Big", tamilName: "Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®ÂªÃ Â¯â€ Ã Â®Â°Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â", category: "Ground Chakkars", price: 80, unit: "Pkt", netRate: false, available: true },
  { id: 30, name: "Ground Chakkar Ashoka", tamilName: "Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®â€¦Ã Â®Å¡Ã Â¯â€¹Ã Â®â€¢Ã Â®Â¾", category: "Ground Chakkars", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 31, name: "Ground Chakkar Special", tamilName: "Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€ Ã Â®Â·Ã Â®Â²Ã Â¯Â", category: "Ground Chakkars", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 32, name: "Ground Chakkar Deluxe", tamilName: "Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 33, name: "AnandaÃ¢â‚¬â„¢s Ground Chakkar Spl", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€ Ã Â®Â·Ã Â®Â²Ã Â¯Â", category: "Ground Chakkars", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 34, name: "AnandaÃ¢â‚¬â„¢s Classic Wheel", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â Ã Â®â€¢Ã Â®Â¿Ã Â®Â³Ã Â®Â¾Ã Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â¯Â Ã Â®ÂµÃ Â¯â‚¬Ã Â®Â²Ã Â¯Â", category: "Ground Chakkars", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 35, name: "Rottas Wheel - Ayyan", tamilName: "Ã Â®Â°Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¸Ã Â¯Â Ã Â®ÂµÃ Â¯â‚¬Ã Â®Â²Ã Â¯Â - Ã Â®â€¦Ã Â®Â¯Ã Â¯ÂÃ Â®Â¯Ã Â®Â©Ã Â¯Â", category: "Ground Chakkars", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 36, name: "Whistling Wheel - Ayyan", tamilName: "Ã Â®ÂµÃ Â®Â¿Ã Â®Å¡Ã Â®Â¿Ã Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®ÂµÃ Â¯â‚¬Ã Â®Â²Ã Â¯Â - Ã Â®â€¦Ã Â®Â¯Ã Â¯ÂÃ Â®Â¯Ã Â®Â©Ã Â¯Â", category: "Ground Chakkars", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 37, name: "Ananda's 3-1 Honda", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â 3-1 Ã Â®Â¹Ã Â¯â€¹Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 38, name: "Ground Chakkar Special Green", tamilName: "Ã Â®Â¤Ã Â®Â°Ã Â¯Ë†Ã Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â®Â®Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€ Ã Â®Â·Ã Â®Â²Ã Â¯Â Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë†", category: "Ground Chakkars", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 39, name: "AnandaÃ¢â‚¬â„¢s Deluxe", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Ground Chakkars", price: 525, unit: "Pkt", netRate: false, available: true },
  { id: 40, name: "AnandaÃ¢â‚¬â„¢s Roller Coaster", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â Ã Â®Â°Ã Â¯â€¹Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â", category: "Ground Chakkars", price: 430, unit: "Pkt", netRate: false, available: true },
  { id: 41, name: "Silver Giant Wheel", tamilName: "Ã Â®Å¡Ã Â®Â¿Ã Â®Â²Ã Â¯ÂÃ Â®ÂµÃ Â®Â°Ã Â¯Â Ã Â®Å“Ã Â¯â€ Ã Â®Â¯Ã Â®Â¿Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®ÂµÃ Â¯â‚¬Ã Â®Â²Ã Â¯Â", category: "Ground Chakkars", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 42, name: "Flower Pots Small", tamilName: "Ã Â®ÂªÃ Â¯â€šÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®Å¡Ã Â®Â¿Ã Â®Â±Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â", category: "Flower Pots", price: 110, unit: "Pkt", netRate: false, available: true },
  { id: 43, name: "Flower Pots Big", tamilName: "Ã Â®ÂªÃ Â¯â€šÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®ÂªÃ Â¯â€ Ã Â®Â°Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â", category: "Flower Pots", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 44, name: "Flower Pots Big Parasakthi", tamilName: "Ã Â®ÂªÃ Â¯â€šÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®ÂªÃ Â¯â€ Ã Â®Â°Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â Ã Â®ÂªÃ Â®Â°Ã Â®Â¾Ã Â®Å¡Ã Â®â€¢Ã Â¯ÂÃ Â®Â¤Ã Â®Â¿", category: "Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 45, name: "Flower Pots Special", tamilName: "Ã Â®ÂªÃ Â¯â€šÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€ Ã Â®Â·Ã Â®Â²Ã Â¯Â", category: "Flower Pots", price: 200, unit: "Pkt", netRate: false, available: true },
  { id: 46, name: "Flower Pots Ashoka", tamilName: "Ã Â®ÂªÃ Â¯â€šÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¦Ã Â®Å¡Ã Â¯â€¹Ã Â®â€¢Ã Â®Â¾", category: "Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 47, name: "F/P DLX (5 Pcs)", tamilName: "F/P Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â (5 Pcs)", category: "Flower Pots", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 48, name: "Colour Koti", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿", category: "Flower Pots", price: 495, unit: "Pkt", netRate: false, available: true },
  { id: 49, name: "Colour Changing", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Å¡Ã Â¯â€¡Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "Flower Pots", price: 320, unit: "Pkt", netRate: false, available: true },
  { id: 50, name: "Crackling Tree", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯â‚¬", category: "Flower Pots", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 51, name: "Toys Fountion", tamilName: "Ã Â®Å¸Ã Â®Â¾Ã Â®Â¯Ã Â¯ÂÃ Â®Â¸Ã Â¯Â Ã Â®ÂªÃ Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â", category: "Flower Pots", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 52, name: "Colour Koti Green (5 Pcs)", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®ÂªÃ Â®Å¡Ã Â¯ÂÃ Â®Å¡Ã Â¯Ë† (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Fancy Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 53, name: "Colour Koti (10 Pcs)", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ (10 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Fancy Flower Pots", price: 1100, unit: "Pkt", netRate: false, available: true },
  { id: 54, name: "Coluour Koti (5 Pcs) Deluxe", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â) Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 55, name: "Coluour Koti (10 Pcs) Deluxe", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ (10 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â) Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Fancy Flower Pots", price: 900, unit: "Pkt", netRate: false, available: true },
  { id: 56, name: "Skype / Twitter", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®â€¢Ã Â¯Ë†Ã Â®ÂªÃ Â¯Â / Ã Â®Å¸Ã Â¯ÂÃ Â®ÂµÃ Â®Â¿Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â", category: "Fancy Flower Pots", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 57, name: "Fantasy Peacock", tamilName: "Ã Â®ÂªÃ Â®Â¾Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â¸Ã Â®Â¿ Ã Â®ÂªÃ Â¯â‚¬Ã Â®â€¢Ã Â®Â¾Ã Â®â€¢Ã Â¯Â", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 58, name: "Jolly Ranger", tamilName: "Ã Â®Å“Ã Â®Â¾Ã Â®Â²Ã Â®Â¿ Ã Â®Â°Ã Â¯â€¡Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â®Â°Ã Â¯Â", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 59, name: "Leaman Tree =Poppings", tamilName: "Ã Â®Â²Ã Â¯â€ Ã Â®Â®Ã Â®Â©Ã Â¯Â Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯â‚¬ Ã Â®ÂªÃ Â®Â¾Ã Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â®Â¿Ã Â®â„¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 60, name: "Tri Colour Fountatin", tamilName: "Ã Â®Â¤Ã Â¯ÂÃ Â®Â°Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â", category: "Fancy Flower Pots", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 61, name: "Selfie Stick (5Pcs) Ananda's", tamilName: "Ã Â®Å¡Ã Â¯â€ Ã Â®Â²Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿ Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®â€¢Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â) Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â¸Ã Â¯Â", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 62, name: "Selfie Stick (5Pcs)", tamilName: "Ã Â®Å¡Ã Â¯â€ Ã Â®Â²Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿ Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®â€¢Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 63, name: "1Ã‚Â½Ã¢â‚¬Â Twinkling Star", tamilName: "1Ã‚Â½Ã¢â‚¬Â Ã Â®Å¡Ã Â®Â¾Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â¯Ë†", category: "Twinkling Star", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 64, name: "4Ã¢â‚¬Â Twinkling Star", tamilName: "4Ã¢â‚¬Â Ã Â®Å¡Ã Â®Â¾Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â¯Ë†", category: "Twinkling Star", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 65, name: "Roman Candles", tamilName: "Ã Â®Â°Ã Â¯â€¹Ã Â®Â®Ã Â®Â©Ã Â¯Â Ã Â®â€¢Ã Â¯â€¡Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®Â²Ã Â¯Â", category: "Twinkling Star", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 66, name: "Bijili (50 Pcs)", tamilName: "Ã Â®ÂªÃ Â®Â¿Ã Â®Å“Ã Â®Â¿Ã Â®Â²Ã Â®Â¿ (50 Pcs)", category: "Bijili", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 67, name: "Red Bijili (100 Pcs)", tamilName: "Ã Â®Å¡Ã Â®Â¿Ã Â®ÂµÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®Å“Ã Â®Â¿Ã Â®Â²Ã Â®Â¿ (100 Pcs)", category: "Bijili", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 68, name: "Stripped Bijili (100 Pcs)", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯Ë†Ã Â®ÂªÃ Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®Å“Ã Â®Â¿Ã Â®Â²Ã Â®Â¿ (100 Pcs)", category: "Bijili", price: 70, unit: "Pkt", netRate: false, available: true },
  { id: 69, name: "2Ã‚Â¾Ã¢â‚¬ÂBird", tamilName: "2Ã‚Â¾Ã¢â‚¬Â Ã Â®ÂªÃ Â¯â€¡Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "Sound Crackers", price: 20, unit: "Pkt", netRate: false, available: true },
  { id: 70, name: "3Ã‚Â½Ã¢â‚¬ÂLakshmi", tamilName: "3Ã‚Â½Ã¢â‚¬Â Ã Â®Â²Ã Â®Å¸Ã Â¯ÂÃ Â®Å¡Ã Â¯ÂÃ Â®Â®Ã Â®Â¿", category: "Sound Crackers", price: 30, unit: "Pkt", netRate: false, available: true },
  { id: 71, name: "4Ã¢â‚¬Â Lakshmi", tamilName: "4Ã¢â‚¬Â Ã Â®Â²Ã Â®Å¸Ã Â¯ÂÃ Â®Å¡Ã Â¯ÂÃ Â®Â®Ã Â®Â¿", category: "Sound Crackers", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 72, name: "4Ã¢â‚¬Â Lakshmi Deluxe", tamilName: "4Ã¢â‚¬Â Ã Â®Â²Ã Â®Å¸Ã Â¯ÂÃ Â®Å¡Ã Â¯ÂÃ Â®Â®Ã Â®Â¿ Ã Â®Å¸Ã Â¯â‚¬Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 73, name: "4Ã¢â‚¬Â Gold Lakshmi", tamilName: "4Ã¢â‚¬Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®Â²Ã Â®Å¸Ã Â¯ÂÃ Â®Å¡Ã Â¯ÂÃ Â®Â®Ã Â®Â¿", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 74, name: "Hulk", tamilName: "Ã Â®Â¹Ã Â®Â²Ã Â¯ÂÃ Â®â€¢Ã Â¯Â", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 75, name: "2 Sound", tamilName: "2 Ã Â®Å¡Ã Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 76, name: "Bahubali", tamilName: "Ã Â®ÂªÃ Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®ÂªÃ Â®Â²Ã Â®Â¿", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 77, name: "Joker/ Lion", tamilName: "Ã Â®Å“Ã Â¯â€¹Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â°Ã Â¯Â / Ã Â®Â²Ã Â®Â¯Ã Â®Â©Ã Â¯Â", category: "Sound Crackers", price: 100, unit: "Pkt", netRate: false, available: true },
  { id: 78, name: "Rocket Bomb", tamilName: "Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â¯â€ Ã Â®Å¸Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Rocket", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 79, name: "Whistling Rocket (5 Pcs)", tamilName: "Ã Â®ÂµÃ Â®Â¿Ã Â®Å¡Ã Â®Â¿Ã Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â¯â€ Ã Â®Å¸Ã Â¯Â (5 Pcs)", category: "Rocket", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 80, name: "Whistling Rocket (10 Pcs)", tamilName: "Ã Â®ÂµÃ Â®Â¿Ã Â®Å¡Ã Â®Â¿Ã Â®Â²Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®Â°Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â¯â€ Ã Â®Å¸Ã Â¯Â (10 Pcs)", category: "Rocket", price: 485, unit: "Pkt", netRate: false, available: true },
  { id: 81, name: "Fancy Peacock", tamilName: "Ã Â®Æ’Ã Â®ÂªÃ Â¯â€¡Ã Â®Â©Ã Â¯ÂÃ Â®Å¡Ã Â®Â¿ Ã Â®ÂªÃ Â¯â‚¬Ã Â®â€¢Ã Â®Â¾Ã Â®â€¢Ã Â¯Â", category: "Rocket", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 82, name: "Tri colour fountatin Small", tamilName: "Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯Ë†Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â Ã Â®Å¡Ã Â®Â¿Ã Â®Â±Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â", category: "Rocket", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 83, name: "Bullet Bomb", tamilName: "Ã Â®ÂªÃ Â¯ÂÃ Â®Â²Ã Â¯ÂÃ Â®Â²Ã Â®Å¸Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 84, name: "Atom Bomb", tamilName: "Ã Â®â€ Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â®Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 85, name: "Hydro Bomb", tamilName: "Ã Â®Â¹Ã Â¯Ë†Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯â€¹ Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 145, unit: "Pkt", netRate: false, available: true },
  { id: 86, name: "King of King", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®â„¢Ã Â¯Â Ã Â®â€ Ã Â®ÂªÃ Â¯Â Ã Â®â€¢Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "Bombs", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 87, name: "Marathan Bomb", tamilName: "Ã Â®Â®Ã Â®Â¾Ã Â®Â°Ã Â®Â¤Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 88, name: "Classic Bomb", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Â³Ã Â®Â¾Ã Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 89, name: "Agni", tamilName: "Ã Â®Å“Ã Â¯â€šÃ Â®Â°Ã Â®Â¾Ã Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 395, unit: "Pkt", netRate: false, available: true },
  { id: 90, name: "555 Bomb", tamilName: "555 Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 91, name: "Killer Bomb", tamilName: "Ã Â®Å¡Ã Â®Â¿Ã Â®Â²Ã Â¯ÂÃ Â®ÂµÃ Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 92, name: "D T S Bomb", tamilName: "Ã Â®Å¸Ã Â®Â¿ Ã Â®Å¸Ã Â®Â¿ Ã Â®Å½Ã Â®Â¸Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â®Ã Â¯Â", category: "Bombs", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 93, name: "Assorted Cartoon (10 Pcs)", tamilName: "Ã Â®â€¦Ã Â®Å¡Ã Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Å¸Ã Â¯Â Ã Â®â€¢Ã Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â¯â€šÃ Â®Â©Ã Â¯Â (10 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 94, name: "Electric Stone / Kit Kat", tamilName: "Ã Â®Å½Ã Â®Â²Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯â€¹Ã Â®Â©Ã Â¯Â", category: "Elite Series", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 95, name: "Jee Boom Baa", tamilName: "Ã Â®Å“Ã Â¯â‚¬ Ã Â®ÂªÃ Â¯â€šÃ Â®Â®Ã Â¯Â Ã Â®ÂªÃ Â®Â¾", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 96, name: "Photo Flash", tamilName: "Ã Â®ÂªÃ Â¯â€¹Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â¯â€¹ Ã Â®ÂªÃ Â®Â¿Ã Â®Â³Ã Â®Â¾Ã Â®Â·Ã Â¯Â", category: "Elite Series", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 97, name: "Selfie Stick (5 Pcs)", tamilName: "Ã Â®Å¡Ã Â¯â€ Ã Â®Â²Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿ Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®â€¢Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 98, name: "Child money bank", tamilName: "Ã Â®Å¡Ã Â¯Ë†Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®Â®Ã Â®Â©Ã Â®Â¿ Ã Â®ÂªÃ Â¯â€¡Ã Â®â„¢Ã Â¯ÂÃ Â®â€¢Ã Â¯Â", category: "Elite Series", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 99, name: "Drone", tamilName: "Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯â€¹Ã Â®Â©Ã Â¯Â", category: "Elite Series", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 100, name: "Pambaram (10 Pcs)", tamilName: "Ã Â®ÂªÃ Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â°Ã Â®Â®Ã Â¯Â (10 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 101, name: "Helicoptar (5 Pcs)", tamilName: "Ã Â®Â¹Ã Â¯â€ Ã Â®Â²Ã Â®Â¿Ã Â®â€¢Ã Â®Â¾Ã Â®ÂªÃ Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 102, name: "Butterfly", tamilName: "Ã Â®ÂªÃ Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿Ã Â®Â³Ã Â¯Ë†", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 103, name: "Sky Shot", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®â€¢Ã Â¯Ë† Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 104, name: "Killar Shot", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Â²Ã Â¯ÂÃ Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Elite Series", price: 270, unit: "Pkt", netRate: false, available: true },
  { id: 105, name: "Colour Fountain (5 Pcs)", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 106, name: "Thriller Siren Big (3 Pcs)", tamilName: "Ã Â®Â¤Ã Â¯ÂÃ Â®Â°Ã Â®Â¿Ã Â®Â²Ã Â¯ÂÃ Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Å¡Ã Â¯Ë†Ã Â®Â°Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®â€¢Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 107, name: "Siren Small (3 Pcs)", tamilName: "Ã Â®Å¡Ã Â¯Ë†Ã Â®Â°Ã Â®Â©Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®Â®Ã Â®Â¾Ã Â®Â²Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 276, unit: "Pkt", netRate: false, available: true },
  { id: 108, name: "Siren Big (2 Pcs)", tamilName: "Ã Â®Å¡Ã Â¯Ë†Ã Â®Â°Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®â€¢Ã Â¯Â (2 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 109, name: "Tin Fountain", tamilName: "Ã Â®Å¸Ã Â®Â¿Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®ÂµÃ Â¯ÂÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 110, name: "Water Queen Falls", tamilName: "Ã Â®ÂµÃ Â®Â¾Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â¯ÂÃ Â®Â¯Ã Â®Â¿Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â²Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Elite Series", price: 360, unit: "Pkt", netRate: false, available: true },
  { id: 111, name: "Colour Fog (5 Pcs)", tamilName: "Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â¯â€¹Ã Â®â€¢Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 112, name: "Pada Peacock", tamilName: "Ã Â®ÂªÃ Â®Å¸Ã Â®Â¾ Ã Â®ÂªÃ Â¯â‚¬Ã Â®â€¢Ã Â®Â¾Ã Â®â€¢Ã Â¯Â", category: "Elite Series", price: 840, unit: "Pkt", netRate: false, available: true },
  { id: 113, name: "Master Cricket Pat", tamilName: "Ã Â®Â®Ã Â®Â¾Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â¯â€ Ã Â®Å¸Ã Â¯Â Ã Â®ÂªÃ Â¯â€¡Ã Â®Å¸Ã Â¯Â", category: "Elite Series", price: 354, unit: "Pcs", netRate: false, available: true },
  { id: 114, name: "Robin Max Cone", tamilName: "Ã Â®Â°Ã Â®Â¾Ã Â®ÂªÃ Â®Â¿Ã Â®Â©Ã Â¯Â Ã Â®Â®Ã Â¯â€¡Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â Ã Â®â€¢Ã Â¯â€¹Ã Â®Â©Ã Â¯Â", category: "Colour Matches", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 115, name: "Super King", tamilName: "Ã Â®Å¡Ã Â¯â€šÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â®Â°Ã Â¯Â Ã Â®â€¢Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "Colour Matches", price: 168, unit: "Pkt", netRate: false, available: true },
  { id: 116, name: "Classic 5 in 1", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Â³Ã Â®Â¾Ã Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â¯Â 5 Ã Â®â€¡Ã Â®Â©Ã Â¯Â 1", category: "Colour Matches", price: 288, unit: "Pkt", netRate: false, available: true },
  { id: 117, name: "7 up Rainbow", tamilName: "7 up Ã Â®Â°Ã Â¯â€ Ã Â®Â¯Ã Â®Â¿Ã Â®Â©Ã Â¯ÂÃ Â®ÂªÃ Â¯â€¹", category: "Colour Matches", price: 312, unit: "Pkt", netRate: false, available: true },
  { id: 118, name: "VIP 10 in 1 Laptop", tamilName: "Ã Â®ÂµÃ Â®Â¿Ã Â®ÂÃ Â®ÂªÃ Â®Â¿ 10 Ã Â®â€¡Ã Â®Â©Ã Â¯Â 1 Ã Â®Â²Ã Â¯â€¡Ã Â®ÂªÃ Â¯ÂÃ Â®Å¸Ã Â®Â¾Ã Â®ÂªÃ Â¯Â", category: "Colour Matches", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 119, name: "Roll cap", tamilName: "Ã Â®Â°Ã Â¯â€¹Ã Â®Â²Ã Â¯Â Ã Â®â€¢Ã Â¯â€¡Ã Â®ÂªÃ Â¯Â", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 120, name: "Black serpent Big", tamilName: "Ã Â®ÂªÃ Â®Â¿Ã Â®Â³Ã Â®Â¾Ã Â®â€¢Ã Â¯Â Ã Â®Å¡Ã Â®Â°Ã Â¯ÂÃ Â®ÂªÃ Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®ÂªÃ Â¯â€ Ã Â®Â°Ã Â®Â¿Ã Â®Â¯Ã Â®Â¤Ã Â¯Â", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 121, name: "Anaconda", tamilName: "Ã Â®â€¦Ã Â®Â©Ã Â®â€¢Ã Â¯â€¹Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾", category: "Ring Cap & Serpent Eggs", price: 192, unit: "Pkt", netRate: false, available: true },
  { id: 122, name: "Epson", tamilName: "Ã Â®Å½Ã Â®ÂªÃ Â¯ÂÃ Â®Å¡Ã Â®Â©Ã Â¯Â", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 123, name: "Fuji", tamilName: "Ã Â®ÂªÃ Â¯ÂÃ Â®Å“Ã Â®Â¿", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 124, name: "Kodak", tamilName: "Ã Â®â€¢Ã Â¯â€¹Ã Â®Å¸Ã Â®Â¾Ã Â®â€¢Ã Â¯Â", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 125, name: "Canan", tamilName: "Ã Â®â€¢Ã Â¯â€ Ã Â®Â©Ã Â®Â¾Ã Â®Â©Ã Â¯Â", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 126, name: "Yellow MG", tamilName: "Ã Â®Â®Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â®Â³Ã Â¯Â Ã Â®Å½Ã Â®Â®Ã Â¯Â Ã Â®Å“Ã Â®Â¿", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 127, name: "Orange Audi", tamilName: "Ã Â®â€ Ã Â®Â°Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â¯Â Ã Â®â€ Ã Â®Å¸Ã Â®Â¿", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 128, name: "Red Swift", tamilName: "Ã Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â¯Â Ã Â®Å¡Ã Â®Â¿Ã Â®ÂªÃ Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 129, name: "Pink Jaguer", tamilName: "Ã Â®ÂªÃ Â®Â¿Ã Â®â„¢Ã Â¯ÂÃ Â®â€¢Ã Â¯Â Ã Â®Å“Ã Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â¯ÂÃ Â®ÂµÃ Â®Â¾Ã Â®Â°Ã Â¯Â", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 130, name: "Blue Land Rover", tamilName: "Ã Â®ÂªÃ Â¯ÂÃ Â®Â³Ã Â¯â€š Ã Â®Â²Ã Â¯â€¡Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®Â°Ã Â¯â€¹Ã Â®ÂµÃ Â®Â°Ã Â¯Â", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 131, name: "Eagle", tamilName: "Ã Â®Ë†Ã Â®â€¢Ã Â®Â¿Ã Â®Â²Ã Â¯Â", category: "3Ã‚Â½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 132, name: "Blood Shot", tamilName: "Ã Â®ÂªÃ Â®Â¿Ã Â®Â³Ã Â®Å¸Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "3Ã‚Â½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 133, name: "Stay Strong", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯â€¡ Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â®Â¾Ã Â®â„¢Ã Â¯Â", category: "3Ã‚Â½\" Rainbow Sky", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 134, name: "Chori 3Ã‚Â½Double Ball", tamilName: "Ã Â®Å¡Ã Â¯â€¹Ã Â®Â°Ã Â®Â¿ 3Ã‚Â½ Ã Â®Å¸Ã Â®ÂªÃ Â¯ÂÃ Â®Â³Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â²Ã Â¯Â", category: "3Ã‚Â½\" Rainbow Sky", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 135, name: "Racing", tamilName: "Ã Â®Â°Ã Â¯â€¡Ã Â®Å¡Ã Â®Â¿Ã Â®â„¢Ã Â¯Â", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 136, name: "Hunter", tamilName: "Ã Â®Â¹Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 137, name: "Passion", tamilName: "Ã Â®ÂªÃ Â¯â€¡Ã Â®Å¡Ã Â®Â¿Ã Â®Â¯Ã Â®Â©Ã Â¯Â", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 138, name: "Volley Ball", tamilName: "Ã Â®ÂµÃ Â®Â¾Ã Â®Â²Ã Â®Â¿ Ã Â®ÂªÃ Â®Â¾Ã Â®Â²Ã Â¯Â", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 139, name: "Nayakara", tamilName: "Ã Â®Â¨Ã Â®Â¯Ã Â®Â¾Ã Â®â€¢Ã Â®Â°Ã Â®Â¾", category: "4\" Mega Sky", price: 680, unit: "Pcs", netRate: false, available: true },
  { id: 140, name: "1Ã¢â‚¬ÂFanta(5 Pcs)", tamilName: "1Ã¢â‚¬Â Ã Â®Æ’Ã Â®ÂªÃ Â¯â€¡Ã Â®Â©Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾ (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 141, name: "1Ã¢â‚¬Â DSLR (5 Pcs)", tamilName: "1Ã¢â‚¬Â Ã Â®Å¸Ã Â®Â¿ Ã Â®Å½Ã Â®Â¸Ã Â¯Â Ã Â®Å½Ã Â®Â²Ã Â¯Â Ã Â®â€ Ã Â®Â°Ã Â¯Â (5 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 575, unit: "Pkt", netRate: false, available: true },
  { id: 142, name: "2Ã¢â‚¬Â Combo (3 Pcs)", tamilName: "2Ã¢â‚¬Â Ã Â®â€¢Ã Â®Â¾Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â¯â€¹ (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 143, name: "2Ã¢â‚¬Â Combo Elite (3 Pcs)", tamilName: "2Ã¢â‚¬Â Ã Â®â€¢Ã Â®Â¾Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â¯â€¹ Ã Â®Å½Ã Â®Â²Ã Â¯Ë†Ã Â®Å¸Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 144, name: "Anandas 3Ã¢â‚¬Â Comets (1 Pcs)", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾ 3Ã¢â‚¬Â Ã Â®â€¢Ã Â®Â¾Ã Â®Â®Ã Â¯â€ Ã Â®Å¸Ã Â¯ÂÃ Â®Â¸Ã Â¯Â (1 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 145, name: "Anandas 3Ã¢â‚¬ÂDouble ball (1Pcs)", tamilName: "Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾ 3Ã¢â‚¬Â Ã Â®Å¸Ã Â®ÂªÃ Â¯ÂÃ Â®Â³Ã Â¯ÂÃ Â®ÂªÃ Â®Â¾Ã Â®Â²Ã Â¯Â (1 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 1000, unit: "Pkt", netRate: false, available: true },
  { id: 146, name: "2Ã‚Â¼Ã¢â‚¬Â Tangled (3 Pcs)AnandaÃ¢â‚¬â„¢s", tamilName: "2Ã‚Â¼Ã¢â‚¬Â Ã Â®Å¸Ã Â¯â€¡Ã Â®â„¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â¿Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 147, name: "2Ã‚Â¼Ã¢â‚¬Â Ice age (3 Pcs)AnandaÃ¢â‚¬â„¢s", tamilName: "2Ã‚Â¼Ã¢â‚¬Â Ã Â®ÂÃ Â®Â¸Ã Â¯Â Ã Â®ÂÃ Â®Å“Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 148, name: "2Ã‚Â¾Ã¢â‚¬ÂCars (3 Pcs) AnandaÃ¢â‚¬â„¢s", tamilName: "2Ã‚Â¾Ã¢â‚¬Â Ã Â®â€¢Ã Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Â¸Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 149, name: "2Ã‚Â¾Ã¢â‚¬ÂTarzen (3 Pcs) AnandaÃ¢â‚¬â„¢s", tamilName: "2Ã‚Â¾Ã¢â‚¬Â Ã Â®Å¸Ã Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Å¡Ã Â®Â©Ã Â¯Â (3 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 150, name: "3\" 8 Steps Captain America 1 Pcs", tamilName: "3Ã¢â‚¬Â 8 Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯â€ Ã Â®ÂªÃ Â¯ÂÃ Â®Â¸Ã Â¯Â Ã Â®â€¦Ã Â®Â®Ã Â¯â€ Ã Â®Â°Ã Â®Â¿Ã Â®â€¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â¾ (1 Ã Â®ÂªÃ Â¯â‚¬Ã Â®Â¸Ã Â¯Â)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 151, name: "Mighty Sword AnandaÃ¢â‚¬â„¢s", tamilName: "Ã Â®Â®Ã Â¯Ë†Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®Â¸Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®ÂµÃ Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾", category: "Combo Aerial Shot", price: 600, unit: "Box", netRate: false, available: true },
  { id: 152, name: "Dirates gun AnandaÃ¢â‚¬â„¢s", tamilName: "Ã Â®Å¸Ã Â¯Ë†Ã Â®Â°Ã Â®â€¢Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®â€¢Ã Â®Â©Ã Â¯Â Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾", category: "Combo Aerial Shot", price: 500, unit: "Box", netRate: false, available: true },
  { id: 153, name: "Five Falls", tamilName: "Ã Â®ÂªÃ Â¯Ë† Ã Â®ÂªÃ Â®Â¾Ã Â®Â²Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Multi Shot", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 154, name: "7 Wonders", tamilName: "7 Ã Â®ÂµÃ Â¯Å Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Multi Shot", price: 205, unit: "Pkt", netRate: false, available: true },
  { id: 155, name: "Space Warriors", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€¡Ã Â®Â¸Ã Â¯Â Ã Â®ÂµÃ Â¯â€¡Ã Â®Â°Ã Â®Â¿Ã Â®Â¯Ã Â®Â°Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Multi Shot", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 156, name: "7 Shot", tamilName: "7 Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Multi Shot", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 157, name: "12 Shots", tamilName: "12 Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Multi Shot", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 158, name: "Kinder pop", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®ÂªÃ Â¯Â", category: "New Version", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 159, name: "Star Pots", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾Ã Â®Â°Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Å¸Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "New Version", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 160, name: "Golden Egg (2 Pcs)", tamilName: "Ã Â®â€¢Ã Â¯â€¹Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â©Ã Â¯Â Ã Â®Å½Ã Â®â€¢Ã Â¯Â (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 161, name: "Gun Spark (2 Pcs)", tamilName: "Ã Â®â€¢Ã Â®Â©Ã Â¯Â Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®â€¢Ã Â¯Â (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 162, name: "Gadayutham", tamilName: "Ã Â®â€¢Ã Â®Å¸Ã Â®Â¾Ã Â®Â¯Ã Â¯ÂÃ Â®Â¤Ã Â®Â®Ã Â¯Â", category: "New Version", price: 415, unit: "Pcs", netRate: false, available: true },
  { id: 163, name: "Feather Super", tamilName: "Ã Â®ÂªÃ Â¯â€ Ã Â®Â¤Ã Â®Â°Ã Â¯Â Ã Â®Å¡Ã Â¯â€šÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â®Â°Ã Â¯Â", category: "New Version", price: 215, unit: "Pcs", netRate: false, available: true },
  { id: 164, name: "Spl Guitor", tamilName: "Ã Â®Â¸Ã Â¯ÂÃ Â®ÂªÃ Â¯â€ Ã Â®Â·Ã Â®Â²Ã Â¯Â Ã Â®â€¢Ã Â®Â¿Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾Ã Â®Â°Ã Â¯Â", category: "New Version", price: 420, unit: "Pcs", netRate: false, available: true },
  { id: 165, name: "Guitor Music Band", tamilName: "Ã Â®â€¢Ã Â®Â¿Ã Â®Å¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¾Ã Â®Â°Ã Â¯Â Ã Â®Â®Ã Â®Â¿Ã Â®Â¯Ã Â¯â€šÃ Â®Å¡Ã Â®Â¿Ã Â®â€¢Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "New Version", price: 600, unit: "Pcs", netRate: false, available: true },
  { id: 166, name: "Red Sun - Sun Feast (5 P-5W)", tamilName: "Ã Â®Â°Ã Â¯â€ Ã Â®Å¸Ã Â¯Â-Ã Â®Å¡Ã Â®Â©Ã Â¯Â-Ã Â®Å¡Ã Â®Â©Ã Â¯Â Ã Â®ÂªÃ Â®Â¿Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â¯Â (5 P-5W)", category: "New Version", price: 385, unit: "Pcs", netRate: false, available: true },
  { id: 167, name: "Hand Shot", tamilName: "Ã Â®Â¹Ã Â¯â€¡Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "New Version", price: 2450, unit: "Pcs", netRate: false, available: true },
  { id: 168, name: "CSK Bus Tricolour", tamilName: "CSK Ã Â®ÂªÃ Â®Â¸Ã Â¯Â Ã Â®Å¸Ã Â¯ÂÃ Â®Â°Ã Â¯Ë†Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â", category: "New Version", price: 580, unit: "Pcs", netRate: false, available: true },
  { id: 169, name: "15 Multi Colour Shot", tamilName: "15 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 275, unit: "Pcs", netRate: true, available: true },
  { id: 170, name: "25 Raider Shot", tamilName: "25 Ã Â®Â°Ã Â¯Ë†Ã Â®Å¸Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 350, unit: "Pcs", netRate: true, available: true },
  { id: 171, name: "30 Multi Colour Shot", tamilName: "30 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: null, unit: "Pcs", netRate: true, available: false, priceText: "Ã¢â€šÂ¹450 / Ã¢â€šÂ¹500" },
  { id: 172, name: "60 Multi Colour Shot", tamilName: "60 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 900, unit: "Pcs", netRate: true, available: true },
  { id: 173, name: "100 Multi Colour Shot", tamilName: "100 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 1600, unit: "Pcs", netRate: true, available: true },
  { id: 174, name: "120 Multi Colour Shot", tamilName: "120 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 1800, unit: "Pcs", netRate: true, available: true },
  { id: 175, name: "10 x 10 AnandaÃ¢â‚¬â„¢s Multi Colour Shot", tamilName: "10 x10 Ã Â®â€ Ã Â®Â©Ã Â®Â¨Ã Â¯ÂÃ Â®Â¤Ã Â®Â¾'Ã Â®Â¸Ã Â¯Â Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 3750, unit: "Pcs", netRate: true, available: true },
  { id: 176, name: "240 Multi Colour Shot", tamilName: "240 Ã Â®Â®Ã Â®Â²Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿ Ã Â®â€¢Ã Â®Â²Ã Â®Â°Ã Â¯Â Ã Â®Â·Ã Â®Â¾Ã Â®Å¸Ã Â¯Â", category: "Fancy Multi Shots", price: 3600, unit: "Pcs", netRate: true, available: true },
  { id: 177, name: "ICE AGE MINIONS19 ITEMS", tamilName: "Ã Â®ÂÃ Â®Â¸Ã Â¯Â Ã Â®ÂÃ Â®Å“Ã Â¯Â Ã Â®Â®Ã Â®Â¿Ã Â®Â©Ã Â®Â¿Ã Â®Â¯Ã Â®Â©Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Gift Box", price: 275, unit: "Box", netRate: true, available: true },
  { id: 178, name: "Dora 19 ITEMS", tamilName: "Ã Â®Å¸Ã Â¯â€¹Ã Â®Â°Ã Â®Â¾", category: "Gift Box", price: 300, unit: "Box", netRate: true, available: true },
  { id: 179, name: "Festival Box 20 ITEMS", tamilName: "Ã Â®ÂªÃ Â¯â€ Ã Â®Â¸Ã Â¯ÂÃ Â®Å¸Ã Â®Â¿Ã Â®ÂµÃ Â®Â²Ã Â¯Â Ã Â®ÂªÃ Â®Â¾Ã Â®â€¢Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Gift Box", price: 325, unit: "Box", netRate: true, available: true },
  { id: 180, name: "Mono 21 ITEMS", tamilName: "Ã Â®Â®Ã Â¯â€¹Ã Â®Â©Ã Â¯â€¹", category: "Gift Box", price: 350, unit: "Box", netRate: true, available: true },
  { id: 181, name: "Angry Birds 27 ITEMS", tamilName: "Ã Â®â€ Ã Â®â„¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¿ Ã Â®ÂªÃ Â¯â€¡Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯ÂÃ Â®Â¸Ã Â¯Â", category: "Gift Box", price: 450, unit: "Box", netRate: true, available: true },
  { id: 182, name: "Avenger 28 ITEMS", tamilName: "Ã Â®â€¦Ã Â®ÂµÃ Â¯â€ Ã Â®Å¾Ã Â¯ÂÃ Â®Å¡Ã Â®Â°Ã Â¯Â", category: "Gift Box", price: 475, unit: "Box", netRate: true, available: true },
  { id: 183, name: "Avator Super 30 ITEMS", tamilName: "Ã Â®â€¦Ã Â®ÂµÃ Â®Â¤Ã Â®Â¾Ã Â®Â°Ã Â¯Â Ã Â®Å¡Ã Â¯â€šÃ Â®ÂªÃ Â¯ÂÃ Â®ÂªÃ Â®Â°Ã Â¯Â", category: "Gift Box", price: 550, unit: "Box", netRate: true, available: true },
  { id: 184, name: "Hulk 36 ITEMS", tamilName: "Ã Â®Â¹Ã Â®Â²Ã Â¯ÂÃ Â®â€¢Ã Â¯Â", category: "Gift Box", price: 650, unit: "Box", netRate: true, available: true },
  { id: 185, name: "Angry Bird 40 ITEMS", tamilName: "Ã Â®â€ Ã Â®â„¢Ã Â¯ÂÃ Â®â€¢Ã Â®Â¿Ã Â®Â°Ã Â®Â¿ Ã Â®ÂªÃ Â¯â€¡Ã Â®Â°Ã Â¯ÂÃ Â®Å¸Ã Â¯Â", category: "Gift Box", price: 750, unit: "Box", netRate: true, available: true },
  { id: 186, name: "Paradise 45 ITEMS", tamilName: "Ã Â®ÂªÃ Â®Â¾Ã Â®Â°Ã Â®Å¸Ã Â¯Ë†Ã Â®Â¸Ã Â¯Â", category: "Gift Box", price: 850, unit: "Box", netRate: true, available: true },
  { id: 187, name: "Wonderful 50 ITEMS", tamilName: "Ã Â®ÂµÃ Â¯Å Ã Â®Â£Ã Â¯ÂÃ Â®Å¸Ã Â®Â°Ã Â¯ÂÃ Â®ÂªÃ Â¯ÂÃ Â®Â²Ã Â¯Â", category: "Gift Box", price: 1050, unit: "Box", netRate: true, available: true },
  { id: 188, name: "Carnival 55 ITEMS", tamilName: "Ã Â®â€¢Ã Â®Â¾Ã Â®Â°Ã Â¯ÂÃ Â®Â©Ã Â®Â¿Ã Â®ÂµÃ Â®Â²Ã Â¯Â", category: "Gift Box", price: 1250, unit: "Box", netRate: true, available: true },
  { id: 189, name: "VIP Champion 60 ITEMS", tamilName: "Ã Â®ÂµÃ Â®Â¿Ã Â®ÂÃ Â®ÂªÃ Â®Â¿ Ã Â®Å¡Ã Â¯â€¡Ã Â®Â®Ã Â¯ÂÃ Â®ÂªÃ Â®Â¿Ã Â®Â¯Ã Â®Â©Ã Â¯Â", category: "Gift Box", price: 1500, unit: "Box", netRate: true, available: true }
];


/* Global catalogue exports for reliable cross-script loading */
if (typeof window !== "undefined") {
    window.categoryOrder = categoryOrder;
    window.products = products;
}