// SELVA CRACKERS 2026 catalogue
// Source: user-provided 2026 price list.
// Items 44 and 52 have no printed price; item 171 is printed as 450/500,
// so those three are intentionally disabled until a single selling price is confirmed.

const categoryOrder = [
  "Sparklers",
  "Fancy Sparklers",
  "Ground Chakkars",
  "Flower Pots",
  "Fancy Flower Pots",
  "Twinkling Star",
  "Bijili",
  "Sound Crackers",
  "Rocket",
  "Bombs",
  "Elite Series",
  "Colour Matches",
  "Ring Cap & Serpent Eggs",
  "Chotaa Fancy",
  "2 Sky Shooters",
  "3½\" Rainbow Sky",
  "4\" Mega Sky",
  "Combo Aerial Shot",
  "Multi Shot",
  "New Version",
  "Fancy Multi Shots",
  "Gift Box"
];

const products = [
  { id: 1, name: "7 cm Electric sparklers", tamilName: "7 செ.மீ. சாதா கம்பி", category: "Sparklers", price: 24, unit: "Pkt", netRate: false, available: true },
  { id: 2, name: "7 cm Colour sparklers", tamilName: "7 செ.மீ. கலர் கம்பி", category: "Sparklers", price: 26, unit: "Pkt", netRate: false, available: true },
  { id: 3, name: "7 cm Green sparklers", tamilName: "7 செ.மீ. பச்சை கம்பி", category: "Sparklers", price: 32, unit: "Pkt", netRate: false, available: true },
  { id: 4, name: "7 cm Red sparklers", tamilName: "7 செ.மீ. சிவப்பு கம்பி", category: "Sparklers", price: 35, unit: "Pkt", netRate: false, available: true },
  { id: 5, name: "10 cm Electric Sparklers", tamilName: "10 செ.மீ. சாதா கம்பி", category: "Sparklers", price: 39, unit: "Pkt", netRate: false, available: true },
  { id: 6, name: "10 cm Colour Sparklers", tamilName: "10 செ.மீ. கலர் கம்பி", category: "Sparklers", price: 45, unit: "Pkt", netRate: false, available: true },
  { id: 7, name: "10 cm Green Sparklers", tamilName: "10 செ.மீ. பச்சை கம்பி", category: "Sparklers", price: 48, unit: "Pkt", netRate: false, available: true },
  { id: 8, name: "10 cm Red Sparklers", tamilName: "10 செ.மீ. சிவப்பு கம்பி", category: "Sparklers", price: 54, unit: "Pkt", netRate: false, available: true },
  { id: 9, name: "15 cm Electric Sparklers", tamilName: "15 செ.மீ. சாதா கம்பி", category: "Sparklers", price: 104, unit: "Pkt", netRate: false, available: true },
  { id: 10, name: "15 cm Colour Sparklers", tamilName: "15 செ.மீ. கலர் கம்பி", category: "Sparklers", price: 116, unit: "Pkt", netRate: false, available: true },
  { id: 11, name: "15 cm Green Sparklers", tamilName: "15 செ.மீ. பச்சை கம்பி", category: "Sparklers", price: 128, unit: "Pkt", netRate: false, available: true },
  { id: 12, name: "15 cm Red Sparklers", tamilName: "15 செ.மீ. சிவப்பு கம்பி", category: "Sparklers", price: 140, unit: "Pkt", netRate: false, available: true },
  { id: 13, name: "30 cm Electric Sparklers", tamilName: "30 செ.மீ. சாதா கம்பி", category: "Sparklers", price: 108, unit: "Pkt", netRate: false, available: true },
  { id: 14, name: "30 cm Colour Sparklers", tamilName: "30 செ.மீ. கலர் கம்பி", category: "Sparklers", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 15, name: "30 cm Green Sparklers", tamilName: "30 செ.மீ. பச்சை கம்பி", category: "Sparklers", price: 132, unit: "Pkt", netRate: false, available: true },
  { id: 16, name: "30 cm Red Sparklers", tamilName: "30 செ.மீ. சிவப்பு கம்பி", category: "Sparklers", price: 142, unit: "Pkt", netRate: false, available: true },
  { id: 17, name: "50 cm Electric", tamilName: "50 செ.மீ. எலக்ட்ரிக்", category: "Sparklers", price: 308, unit: "Pkt", netRate: false, available: true },
  { id: 18, name: "50 cm Green", tamilName: "50 செ.மீ. பச்சை", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 19, name: "50 cm Colour", tamilName: "50 செ.மீ. கலர்", category: "Sparklers", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 20, name: "10cmMiranda Orange/Mercury/Japan", tamilName: "10 செ.மீ. மிராண்டா ஆரஞ்ச் / மெர்குரி / ஜப்பான்", category: "Fancy Sparklers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 21, name: "50 cm Electric", tamilName: "50 செ.மீ. எலக்ட்ரிக்", category: "Fancy Sparklers", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 22, name: "50 cm Crackling", tamilName: "50 செ.மீ. கிராக்லிங்", category: "Fancy Sparklers", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 23, name: "50 cm 5 in 1 Colour", tamilName: "50 செ.மீ. 5 இன் 1", category: "Fancy Sparklers", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 24, name: "75 cm Electric", tamilName: "75 செ.மீ. எலக்ட்ரிக்", category: "Fancy Sparklers", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 25, name: "75 cm Crackling", tamilName: "75 செ.மீ. கிராக்லிங்", category: "Fancy Sparklers", price: 620, unit: "Pkt", netRate: false, available: true },
  { id: 26, name: "75 cm 5 in 1 Colour", tamilName: "75 செ.மீ. 5 இன் 1 கலர்", category: "Fancy Sparklers", price: 675, unit: "Pkt", netRate: false, available: true },
  { id: 27, name: "Dancing Rose (Ele)", tamilName: "டான்சிங் ரோஸ் எலக்ட்", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 28, name: "Dancing Rose (R & W)", tamilName: "டான்சிங் ரோஸ் (R & W)", category: "Fancy Sparklers", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 29, name: "Ground Chakkar Big", tamilName: "தரைச்சக்கரம் பெரியது", category: "Ground Chakkars", price: 80, unit: "Pkt", netRate: false, available: true },
  { id: 30, name: "Ground Chakkar Ashoka", tamilName: "தரைச்சக்கரம் அசோகா", category: "Ground Chakkars", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 31, name: "Ground Chakkar Special", tamilName: "தரைச்சக்கரம் ஸ்பெஷல்", category: "Ground Chakkars", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 32, name: "Ground Chakkar Deluxe", tamilName: "தரைச்சக்கரம் டீலக்ஸ்", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 33, name: "Ananda’s Ground Chakkar Spl", tamilName: "ஆனந்தாஸ் தரைச்சக்கரம் ஸ்பெஷல்", category: "Ground Chakkars", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 34, name: "Ananda’s Classic Wheel", tamilName: "ஆனந்தாஸ் கிளாசிக் வீல்", category: "Ground Chakkars", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 35, name: "Rottas Wheel - Ayyan", tamilName: "ரோட்டஸ் வீல் - அய்யன்", category: "Ground Chakkars", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 36, name: "Whistling Wheel - Ayyan", tamilName: "விசிலிங் வீல் - அய்யன்", category: "Ground Chakkars", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 37, name: "Ananda's 3-1 Honda", tamilName: "ஆனந்தாஸ் 3-1 ஹோண்டா", category: "Ground Chakkars", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 38, name: "Ground Chakkar Special Green", tamilName: "தரைச்சக்கரம் ஸ்பெஷல் பச்சை", category: "Ground Chakkars", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 39, name: "Ananda’s Deluxe", tamilName: "ஆனந்தாஸ் டீலக்ஸ்", category: "Ground Chakkars", price: 525, unit: "Pkt", netRate: false, available: true },
  { id: 40, name: "Ananda’s Roller Coaster", tamilName: "ஆனந்தாஸ் ரோலர் கோஸ்டர்", category: "Ground Chakkars", price: 430, unit: "Pkt", netRate: false, available: true },
  { id: 41, name: "Silver Giant Wheel", tamilName: "சில்வர் ஜெயிண்ட் வீல்", category: "Ground Chakkars", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 42, name: "Flower Pots Small", tamilName: "பூச்சட்டி சிறியது", category: "Flower Pots", price: 110, unit: "Pkt", netRate: false, available: true },
  { id: 43, name: "Flower Pots Big", tamilName: "பூச்சட்டி பெரியது", category: "Flower Pots", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 44, name: "Flower Pots Big Parasakthi", tamilName: "பூச்சட்டி பெரியது பராசக்தி", category: "Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 45, name: "Flower Pots Special", tamilName: "பூச்சட்டி ஸ்பெஷல்", category: "Flower Pots", price: 200, unit: "Pkt", netRate: false, available: true },
  { id: 46, name: "Flower Pots Ashoka", tamilName: "பூச்சட்டி அசோகா", category: "Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 47, name: "F/P DLX (5 Pcs)", tamilName: "F/P டீலக்ஸ் (5 Pcs)", category: "Flower Pots", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 48, name: "Colour Koti", tamilName: "கலர் கோட்டி", category: "Flower Pots", price: 495, unit: "Pkt", netRate: false, available: true },
  { id: 49, name: "Colour Changing", tamilName: "கலர் சேஞ்சிங்", category: "Flower Pots", price: 320, unit: "Pkt", netRate: false, available: true },
  { id: 50, name: "Crackling Tree", tamilName: "கிராக்லிங் ட்ரீ", category: "Flower Pots", price: 460, unit: "Pkt", netRate: false, available: true },
  { id: 51, name: "Toys Fountion", tamilName: "டாய்ஸ் பவுண்டன்", category: "Flower Pots", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 52, name: "Colour Koti Green (5 Pcs)", tamilName: "கலர் கோட்டி பச்சை (5 பீஸ்)", category: "Fancy Flower Pots", price: null, unit: "Pkt", netRate: false, available: false, priceText: "Price on request" },
  { id: 53, name: "Colour Koti (10 Pcs)", tamilName: "கலர் கோட்டி (10 பீஸ்)", category: "Fancy Flower Pots", price: 1100, unit: "Pkt", netRate: false, available: true },
  { id: 54, name: "Coluour Koti (5 Pcs) Deluxe", tamilName: "கலர் கோட்டி (5 பீஸ்) டீலக்ஸ்", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 55, name: "Coluour Koti (10 Pcs) Deluxe", tamilName: "கலர் கோட்டி (10 பீஸ்) டீலக்ஸ்", category: "Fancy Flower Pots", price: 900, unit: "Pkt", netRate: false, available: true },
  { id: 56, name: "Skype / Twitter", tamilName: "ஸ்கைப் / ட்விட்டர்", category: "Fancy Flower Pots", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 57, name: "Fantasy Peacock", tamilName: "பாண்டஸி பீகாக்", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 58, name: "Jolly Ranger", tamilName: "ஜாலி ரேஞ்சர்", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 59, name: "Leaman Tree =Poppings", tamilName: "லெமன் ட்ரீ பாப்பிங்ஸ்", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 60, name: "Tri Colour Fountatin", tamilName: "த்ரி கலர் பவுண்டன்", category: "Fancy Flower Pots", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 61, name: "Selfie Stick (5Pcs) Ananda's", tamilName: "செல்பி ஸ்டிக் (5 பீஸ்) ஆனந்தாஸ்", category: "Fancy Flower Pots", price: 450, unit: "Pkt", netRate: false, available: true },
  { id: 62, name: "Selfie Stick (5Pcs)", tamilName: "செல்பி ஸ்டிக் (5 பீஸ்)", category: "Fancy Flower Pots", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 63, name: "1½” Twinkling Star", tamilName: "1½” சாட்டை", category: "Twinkling Star", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 64, name: "4” Twinkling Star", tamilName: "4” சாட்டை", category: "Twinkling Star", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 65, name: "Roman Candles", tamilName: "ரோமன் கேண்டில்", category: "Twinkling Star", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 66, name: "Bijili (50 Pcs)", tamilName: "பிஜிலி (50 Pcs)", category: "Bijili", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 67, name: "Red Bijili (100 Pcs)", tamilName: "சிவப்பு பிஜிலி (100 Pcs)", category: "Bijili", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 68, name: "Stripped Bijili (100 Pcs)", tamilName: "ஸ்ட்ரைப்டு பிஜிலி (100 Pcs)", category: "Bijili", price: 70, unit: "Pkt", netRate: false, available: true },
  { id: 69, name: "2¾”Bird", tamilName: "2¾” பேர்டு", category: "Sound Crackers", price: 20, unit: "Pkt", netRate: false, available: true },
  { id: 70, name: "3½”Lakshmi", tamilName: "3½” லட்சுமி", category: "Sound Crackers", price: 30, unit: "Pkt", netRate: false, available: true },
  { id: 71, name: "4” Lakshmi", tamilName: "4” லட்சுமி", category: "Sound Crackers", price: 40, unit: "Pkt", netRate: false, available: true },
  { id: 72, name: "4” Lakshmi Deluxe", tamilName: "4” லட்சுமி டீலக்ஸ்", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 73, name: "4” Gold Lakshmi", tamilName: "4” கோல்டு லட்சுமி", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 74, name: "Hulk", tamilName: "ஹல்க்", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 75, name: "2 Sound", tamilName: "2 சவுண்டு", category: "Sound Crackers", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 76, name: "Bahubali", tamilName: "பாகுபலி", category: "Sound Crackers", price: 75, unit: "Pkt", netRate: false, available: true },
  { id: 77, name: "Joker/ Lion", tamilName: "ஜோக்கர் / லயன்", category: "Sound Crackers", price: 100, unit: "Pkt", netRate: false, available: true },
  { id: 78, name: "Rocket Bomb", tamilName: "ராக்கெட் பாம்", category: "Rocket", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 79, name: "Whistling Rocket (5 Pcs)", tamilName: "விசிலிங் ராக்கெட் (5 Pcs)", category: "Rocket", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 80, name: "Whistling Rocket (10 Pcs)", tamilName: "விசிலிங் ராக்கெட் (10 Pcs)", category: "Rocket", price: 485, unit: "Pkt", netRate: false, available: true },
  { id: 81, name: "Fancy Peacock", tamilName: "ஃபேன்சி பீகாக்", category: "Rocket", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 82, name: "Tri colour fountatin Small", tamilName: "ட்ரைகலர் பவுண்டன் சிறியது", category: "Rocket", price: 400, unit: "Pkt", netRate: false, available: true },
  { id: 83, name: "Bullet Bomb", tamilName: "புல்லட் பாம்", category: "Bombs", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 84, name: "Atom Bomb", tamilName: "ஆட்டம் பாம்", category: "Bombs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 85, name: "Hydro Bomb", tamilName: "ஹைட்ரோ பாம்", category: "Bombs", price: 145, unit: "Pkt", netRate: false, available: true },
  { id: 86, name: "King of King", tamilName: "கிங் ஆப் கிங்", category: "Bombs", price: 195, unit: "Pkt", netRate: false, available: true },
  { id: 87, name: "Marathan Bomb", tamilName: "மாரத்தான் பாம்", category: "Bombs", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 88, name: "Classic Bomb", tamilName: "கிளாசிக் பாம்", category: "Bombs", price: 260, unit: "Pkt", netRate: false, available: true },
  { id: 89, name: "Agni", tamilName: "ஜூராசிக் பாம்", category: "Bombs", price: 395, unit: "Pkt", netRate: false, available: true },
  { id: 90, name: "555 Bomb", tamilName: "555 பாம்", category: "Bombs", price: 285, unit: "Pkt", netRate: false, available: true },
  { id: 91, name: "Killer Bomb", tamilName: "சில்வர் பாம்", category: "Bombs", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 92, name: "D T S Bomb", tamilName: "டி டி எஸ் பாம்", category: "Bombs", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 93, name: "Assorted Cartoon (10 Pcs)", tamilName: "அசார்ட்டடு கார்ட்டூன் (10 பீஸ்)", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 94, name: "Electric Stone / Kit Kat", tamilName: "எலக்ட்ரிக் ஸ்டோன்", category: "Elite Series", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 95, name: "Jee Boom Baa", tamilName: "ஜீ பூம் பா", category: "Elite Series", price: 60, unit: "Pkt", netRate: false, available: true },
  { id: 96, name: "Photo Flash", tamilName: "போட்டோ பிளாஷ்", category: "Elite Series", price: 180, unit: "Pkt", netRate: false, available: true },
  { id: 97, name: "Selfie Stick (5 Pcs)", tamilName: "செல்பி ஸ்டிக் (5 பீஸ்)", category: "Elite Series", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 98, name: "Child money bank", tamilName: "சைல்டு மனி பேங்க்", category: "Elite Series", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 99, name: "Drone", tamilName: "ட்ரோன்", category: "Elite Series", price: 330, unit: "Pkt", netRate: false, available: true },
  { id: 100, name: "Pambaram (10 Pcs)", tamilName: "பம்பரம் (10 பீஸ்)", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 101, name: "Helicoptar (5 Pcs)", tamilName: "ஹெலிகாப்டர் (5 பீஸ்)", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 102, name: "Butterfly", tamilName: "பட்டர்பிளை", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 103, name: "Sky Shot", tamilName: "ஸ்கை ஷாட்", category: "Elite Series", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 104, name: "Killar Shot", tamilName: "கில்லர் ஷாட்", category: "Elite Series", price: 270, unit: "Pkt", netRate: false, available: true },
  { id: 105, name: "Colour Fountain (5 Pcs)", tamilName: "கலர் பவுண்டன் (5 பீஸ்)", category: "Elite Series", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 106, name: "Thriller Siren Big (3 Pcs)", tamilName: "த்ரில்லர் சைரன் பிக் (3 பீஸ்)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 107, name: "Siren Small (3 Pcs)", tamilName: "சைரன் ஸ்மால் (3 பீஸ்)", category: "Elite Series", price: 276, unit: "Pkt", netRate: false, available: true },
  { id: 108, name: "Siren Big (2 Pcs)", tamilName: "சைரன் பிக் (2 பீஸ்)", category: "Elite Series", price: 420, unit: "Pkt", netRate: false, available: true },
  { id: 109, name: "Tin Fountain", tamilName: "டின் பவுண்டன்", category: "Elite Series", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 110, name: "Water Queen Falls", tamilName: "வாட்டர் குயின் பால்ஸ்", category: "Elite Series", price: 360, unit: "Pkt", netRate: false, available: true },
  { id: 111, name: "Colour Fog (5 Pcs)", tamilName: "கலர் போக் (5 பீஸ்)", category: "Elite Series", price: 432, unit: "Pkt", netRate: false, available: true },
  { id: 112, name: "Pada Peacock", tamilName: "படா பீகாக்", category: "Elite Series", price: 840, unit: "Pkt", netRate: false, available: true },
  { id: 113, name: "Master Cricket Pat", tamilName: "மாஸ்டர் கிரிக்கெட் பேட்", category: "Elite Series", price: 354, unit: "Pcs", netRate: false, available: true },
  { id: 114, name: "Robin Max Cone", tamilName: "ராபின் மேக்ஸ் கோன்", category: "Colour Matches", price: 96, unit: "Pkt", netRate: false, available: true },
  { id: 115, name: "Super King", tamilName: "சூப்பர் கிங்", category: "Colour Matches", price: 168, unit: "Pkt", netRate: false, available: true },
  { id: 116, name: "Classic 5 in 1", tamilName: "கிளாசிக் 5 இன் 1", category: "Colour Matches", price: 288, unit: "Pkt", netRate: false, available: true },
  { id: 117, name: "7 up Rainbow", tamilName: "7 up ரெயின்போ", category: "Colour Matches", price: 312, unit: "Pkt", netRate: false, available: true },
  { id: 118, name: "VIP 10 in 1 Laptop", tamilName: "விஐபி 10 இன் 1 லேப்டாப்", category: "Colour Matches", price: 480, unit: "Pkt", netRate: false, available: true },
  { id: 119, name: "Roll cap", tamilName: "ரோல் கேப்", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 120, name: "Black serpent Big", tamilName: "பிளாக் சர்பண்ட் பெரியது", category: "Ring Cap & Serpent Eggs", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 121, name: "Anaconda", tamilName: "அனகோண்டா", category: "Ring Cap & Serpent Eggs", price: 192, unit: "Pkt", netRate: false, available: true },
  { id: 122, name: "Epson", tamilName: "எப்சன்", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 123, name: "Fuji", tamilName: "புஜி", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 124, name: "Kodak", tamilName: "கோடாக்", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 125, name: "Canan", tamilName: "கெனான்", category: "Chotaa Fancy", price: 120, unit: "Pkt", netRate: false, available: true },
  { id: 126, name: "Yellow MG", tamilName: "மஞ்சள் எம் ஜி", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 127, name: "Orange Audi", tamilName: "ஆரஞ்ச் ஆடி", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 128, name: "Red Swift", tamilName: "சிகப்பு சிப்ட்", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 129, name: "Pink Jaguer", tamilName: "பிங்க் ஜாக்குவார்", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 130, name: "Blue Land Rover", tamilName: "புளூ லேண்ட் ரோவர்", category: "2 Sky Shooters", price: 210, unit: "Pkt", netRate: false, available: true },
  { id: 131, name: "Eagle", tamilName: "ஈகில்", category: "3½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 132, name: "Blood Shot", tamilName: "பிளட் ஷாட்", category: "3½\" Rainbow Sky", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 133, name: "Stay Strong", tamilName: "ஸ்டே ஸ்ட்ராங்", category: "3½\" Rainbow Sky", price: 550, unit: "Pkt", netRate: false, available: true },
  { id: 134, name: "Chori 3½Double Ball", tamilName: "சோரி 3½ டபுள் பால்", category: "3½\" Rainbow Sky", price: 800, unit: "Pkt", netRate: false, available: true },
  { id: 135, name: "Racing", tamilName: "ரேசிங்", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 136, name: "Hunter", tamilName: "ஹண்டர்", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 137, name: "Passion", tamilName: "பேசியன்", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 138, name: "Volley Ball", tamilName: "வாலி பால்", category: "4\" Mega Sky", price: 650, unit: "Pcs", netRate: false, available: true },
  { id: 139, name: "Nayakara", tamilName: "நயாகரா", category: "4\" Mega Sky", price: 680, unit: "Pcs", netRate: false, available: true },
  { id: 140, name: "1”Fanta(5 Pcs)", tamilName: "1” ஃபேன்டா (5 பீஸ்)", category: "Combo Aerial Shot", price: 350, unit: "Pkt", netRate: false, available: true },
  { id: 141, name: "1” DSLR (5 Pcs)", tamilName: "1” டி எஸ் எல் ஆர் (5 பீஸ்)", category: "Combo Aerial Shot", price: 575, unit: "Pkt", netRate: false, available: true },
  { id: 142, name: "2” Combo (3 Pcs)", tamilName: "2” காம்போ (3 பீஸ்)", category: "Combo Aerial Shot", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 143, name: "2” Combo Elite (3 Pcs)", tamilName: "2” காம்போ எலைட் (3 பீஸ்)", category: "Combo Aerial Shot", price: 600, unit: "Pkt", netRate: false, available: true },
  { id: 144, name: "Anandas 3” Comets (1 Pcs)", tamilName: "ஆனந்தா 3” காமெட்ஸ் (1 பீஸ்)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 145, name: "Anandas 3”Double ball (1Pcs)", tamilName: "ஆனந்தா 3” டபுள்பால் (1 பீஸ்)", category: "Combo Aerial Shot", price: 1000, unit: "Pkt", netRate: false, available: true },
  { id: 146, name: "2¼” Tangled (3 Pcs)Ananda’s", tamilName: "2¼” டேங்கில்டு (3 பீஸ்)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 147, name: "2¼” Ice age (3 Pcs)Ananda’s", tamilName: "2¼” ஐஸ் ஏஜ் (3 பீஸ்)", category: "Combo Aerial Shot", price: 1200, unit: "Pkt", netRate: false, available: true },
  { id: 148, name: "2¾”Cars (3 Pcs) Ananda’s", tamilName: "2¾” கார்ஸ் (3 பீஸ்)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 149, name: "2¾”Tarzen (3 Pcs) Ananda’s", tamilName: "2¾” டார்சன் (3 பீஸ்)", category: "Combo Aerial Shot", price: 1300, unit: "Pkt", netRate: false, available: true },
  { id: 150, name: "3\" 8 Steps Captain America 1 Pcs", tamilName: "3” 8 ஸ்டெப்ஸ் அமெரிக்கா (1 பீஸ்)", category: "Combo Aerial Shot", price: 850, unit: "Pkt", netRate: false, available: true },
  { id: 151, name: "Mighty Sword Ananda’s", tamilName: "மைட்டிஸ் ஸ்வார்டு ஆனந்தா", category: "Combo Aerial Shot", price: 600, unit: "Box", netRate: false, available: true },
  { id: 152, name: "Dirates gun Ananda’s", tamilName: "டைரக்ட் கன் ஆனந்தா", category: "Combo Aerial Shot", price: 500, unit: "Box", netRate: false, available: true },
  { id: 153, name: "Five Falls", tamilName: "பை பால்ஸ்", category: "Multi Shot", price: 150, unit: "Pkt", netRate: false, available: true },
  { id: 154, name: "7 Wonders", tamilName: "7 வொண்டர்ஸ்", category: "Multi Shot", price: 205, unit: "Pkt", netRate: false, available: true },
  { id: 155, name: "Space Warriors", tamilName: "ஸ்பேஸ் வேரியர்ஸ்", category: "Multi Shot", price: 240, unit: "Pkt", netRate: false, available: true },
  { id: 156, name: "7 Shot", tamilName: "7 ஷாட்", category: "Multi Shot", price: 290, unit: "Pkt", netRate: false, available: true },
  { id: 157, name: "12 Shots", tamilName: "12 ஷாட்ஸ்", category: "Multi Shot", price: 300, unit: "Pkt", netRate: false, available: true },
  { id: 158, name: "Kinder pop", tamilName: "கிண்டர் பாப்", category: "New Version", price: 500, unit: "Pkt", netRate: false, available: true },
  { id: 159, name: "Star Pots", tamilName: "ஸ்டார் பாட்ஸ்", category: "New Version", price: 220, unit: "Pkt", netRate: false, available: true },
  { id: 160, name: "Golden Egg (2 Pcs)", tamilName: "கோல்டன் எக் (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 161, name: "Gun Spark (2 Pcs)", tamilName: "கன் ஸ்பார்க் (2 Pcs)", category: "New Version", price: 325, unit: "Pkt", netRate: false, available: true },
  { id: 162, name: "Gadayutham", tamilName: "கடாயுதம்", category: "New Version", price: 415, unit: "Pcs", netRate: false, available: true },
  { id: 163, name: "Feather Super", tamilName: "பெதர் சூப்பர்", category: "New Version", price: 215, unit: "Pcs", netRate: false, available: true },
  { id: 164, name: "Spl Guitor", tamilName: "ஸ்பெஷல் கிட்டார்", category: "New Version", price: 420, unit: "Pcs", netRate: false, available: true },
  { id: 165, name: "Guitor Music Band", tamilName: "கிட்டார் மியூசிக் பாண்ட்", category: "New Version", price: 600, unit: "Pcs", netRate: false, available: true },
  { id: 166, name: "Red Sun - Sun Feast (5 P-5W)", tamilName: "ரெட்-சன்-சன் பிஸ்ட் (5 P-5W)", category: "New Version", price: 385, unit: "Pcs", netRate: false, available: true },
  { id: 167, name: "Hand Shot", tamilName: "ஹேண்ட் ஷாட்", category: "New Version", price: 2450, unit: "Pcs", netRate: false, available: true },
  { id: 168, name: "CSK Bus Tricolour", tamilName: "CSK பஸ் ட்ரைகலர்", category: "New Version", price: 580, unit: "Pcs", netRate: false, available: true },
  { id: 169, name: "15 Multi Colour Shot", tamilName: "15 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 275, unit: "Pcs", netRate: true, available: true },
  { id: 170, name: "25 Raider Shot", tamilName: "25 ரைடர் ஷாட்", category: "Fancy Multi Shots", price: 350, unit: "Pcs", netRate: true, available: true },
  { id: 171, name: "30 Multi Colour Shot", tamilName: "30 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: null, unit: "Pcs", netRate: true, available: false, priceText: "₹450 / ₹500" },
  { id: 172, name: "60 Multi Colour Shot", tamilName: "60 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 900, unit: "Pcs", netRate: true, available: true },
  { id: 173, name: "100 Multi Colour Shot", tamilName: "100 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 1600, unit: "Pcs", netRate: true, available: true },
  { id: 174, name: "120 Multi Colour Shot", tamilName: "120 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 1800, unit: "Pcs", netRate: true, available: true },
  { id: 175, name: "10 x 10 Ananda’s Multi Colour Shot", tamilName: "10 x10 ஆனந்தா'ஸ் மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 3750, unit: "Pcs", netRate: true, available: true },
  { id: 176, name: "240 Multi Colour Shot", tamilName: "240 மல்டி கலர் ஷாட்", category: "Fancy Multi Shots", price: 3600, unit: "Pcs", netRate: true, available: true },
  { id: 177, name: "ICE AGE MINIONS19 ITEMS", tamilName: "ஐஸ் ஏஜ் மினியன்ஸ்", category: "Gift Box", price: 275, unit: "Box", netRate: true, available: true },
  { id: 178, name: "Dora 19 ITEMS", tamilName: "டோரா", category: "Gift Box", price: 300, unit: "Box", netRate: true, available: true },
  { id: 179, name: "Festival Box 20 ITEMS", tamilName: "பெஸ்டிவல் பாக்ஸ்", category: "Gift Box", price: 325, unit: "Box", netRate: true, available: true },
  { id: 180, name: "Mono 21 ITEMS", tamilName: "மோனோ", category: "Gift Box", price: 350, unit: "Box", netRate: true, available: true },
  { id: 181, name: "Angry Birds 27 ITEMS", tamilName: "ஆங்கிரி பேர்ட்ஸ்", category: "Gift Box", price: 450, unit: "Box", netRate: true, available: true },
  { id: 182, name: "Avenger 28 ITEMS", tamilName: "அவெஞ்சர்", category: "Gift Box", price: 475, unit: "Box", netRate: true, available: true },
  { id: 183, name: "Avator Super 30 ITEMS", tamilName: "அவதார் சூப்பர்", category: "Gift Box", price: 550, unit: "Box", netRate: true, available: true },
  { id: 184, name: "Hulk 36 ITEMS", tamilName: "ஹல்க்", category: "Gift Box", price: 650, unit: "Box", netRate: true, available: true },
  { id: 185, name: "Angry Bird 40 ITEMS", tamilName: "ஆங்கிரி பேர்டு", category: "Gift Box", price: 750, unit: "Box", netRate: true, available: true },
  { id: 186, name: "Paradise 45 ITEMS", tamilName: "பாரடைஸ்", category: "Gift Box", price: 850, unit: "Box", netRate: true, available: true },
  { id: 187, name: "Wonderful 50 ITEMS", tamilName: "வொண்டர்புல்", category: "Gift Box", price: 1050, unit: "Box", netRate: true, available: true },
  { id: 188, name: "Carnival 55 ITEMS", tamilName: "கார்னிவல்", category: "Gift Box", price: 1250, unit: "Box", netRate: true, available: true },
  { id: 189, name: "VIP Champion 60 ITEMS", tamilName: "விஐபி சேம்பியன்", category: "Gift Box", price: 1500, unit: "Box", netRate: true, available: true }
];


/* Global catalogue exports for reliable cross-script loading */
if (typeof window !== "undefined") {
  window.categoryOrder = categoryOrder;
  window.products = products;
}
